trigger:
- dev

pool:
  name: Self hosted pool

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dir $(System.DefaultWorkingDirectory)'
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)'
    artifact: 'MemberPortal'