trigger: none

pool: Self hosted pool

resources:
  repositories:
    - repository: templates
      type: git
      name: "Consumer_Portals/DevOps-Repo"
      ref: refs/heads/dev

steps:
  - template: jobs/next-pipeline.yml@templates
  - task: PowerShell@2
    inputs:
      targetType: 'inline'
      script: 'npm run test'
    displayName: Run Tests From App Config
    continueOnError: true

  - task: PowerShell@2
    inputs:
      targetType: "inline"
      script: "dir $(System.DefaultWorkingDirectory)"
    displayName: Output Src Dir
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: "$(System.DefaultWorkingDirectory)"
      artifact: "MemberPortal"
    displayName: Publish Code Snapshot
