import alertBlueSvg from '@/../public/assets/alert_blue.svg';
import showPasswordSvg from '@/../public/assets/show_password.svg';
import showPasswordSelectedSvg from '@/../public/assets/show_password_selected.svg';
import amplifyHealthAppPromo from '@/public/assets/amplify_health_app.png';
import appleStoreSvg from '@/public/assets/apple_store.svg';
import callSvg from '@/public/assets/call.svg';
import chatSvg from '@/public/assets/chat.svg';
import checkGreenSvg from '@/public/assets/check_green.svg';
import dollarGeneralSvg from '@/public/assets/dollar_general.svg';
import emailSvg from '@/public/assets/email.svg';
import findFormSvg from '@/public/assets/find_form.svg';
import glossarySvg from '@/public/assets/glossary.svg';
import playStoreSvg from '@/public/assets/google_play.svg';
import questionsSvg from '@/public/assets/questions.svg';
import viewLessSvg from '@/public/assets/view_less.svg';
import viewMoreSvg from '@/public/assets/view_more.svg';
import ableToSvg from '../../../public/assets/able_to.svg';
import accessGrantedSvg from '../../../public/assets/access_granted.svg';
import alertErrorSvg from '../../../public/assets/alert_error_red.svg';
import alightSvg from '../../../public/assets/alight.svg';
import bcbstLogoSvg from '../../../public/assets/bcbst_blue.svg';
import bcbstnSvg from '../../../public/assets/bcbstn.svg';
import benefitsSvg from '../../../public/assets/benefits.svg';
import biometricScreeningSvg from '../../../public/assets/biometric_screening.svg';
import blueCrossSilhouletteSvg from '../../../public/assets/bluecross_silhouette.svg';
import bcbstStackedSvg from '../../../public/assets/bluecross_stacked.svg';
import calenderSvg from '../../../public/assets/calendar.svg';
import checkBlueIconSvg from '../../../public/assets/check.svg';
import claimsBenefitsCoverageSvg from '../../../public/assets/claims.svg';
import closeIconSvg from '../../../public/assets/close.svg';
import communicationSettingsSvg from '../../../public/assets/communication_settings.svg';
import connectAccountssvg from '../../../public/assets/connect_accounts.svg';
import costSvg from '../../../public/assets/cost.svg';
import cvsCaremarkSvg from '../../../public/assets/cvs_caremark.svg';
import dentalSvg from '../../../public/assets/dental.svg';
import dentalHealthLibrarySvg from '../../../public/assets/dental_health_library.svg';
import documentFileSvg from '../../../public/assets/document_file.svg';
import downSvg from '../../../public/assets/down.svg';
import downGraySvg from '../../../public/assets/down_gray.svg';
import downloadIconSvg from '../../../public/assets/download.svg';
import enrollmentSvg from '../../../public/assets/enrollment.svg';
import { default as externalSvg } from '../../../public/assets/external.svg';
import externaloffsitewhiteSvg from '../../../public/assets/external_white.svg';
import facebookSvg from '../../../public/assets/facebook_white.svg';
import fitSvg from '../../../public/assets/fitness.svg';
import fitnessSvg from '../../../public/assets/fitness_2.svg';
import globalIdCardSvg from '../../../public/assets/global_id_card.svg';
import hamburgerMenuSvg from '../../../public/assets/hamburger_menu.svg';
import healthAssessmentIconSvg from '../../../public/assets/health_assessment.svg';
import hingeHealthSVG from '../../../public/assets/hinge_health.svg';
import idCardPrimarySvg from '../../../public/assets/id_card.svg';
import inboxSvg from '../../../public/assets/inbox.svg';
import instagramSvg from '../../../public/assets/instagram_white.svg';
import interactiveProgramsIconSvg from '../../../public/assets/interactive_programs.svg';
import keySvg from '../../../public/assets/key.svg';
import leftIconSvg from '../../../public/assets/left.svg';
import linkedInSvg from '../../../public/assets/linkedin_white.svg';
import mailOrderPharmacySvg from '../../../public/assets/mail_order_pharmacy.svg';
import medicalSvg from '../../../public/assets/medical.svg';
import modalAlertSvg from '../../../public/assets/modal_alert.svg';
import basicAccess from '../../../public/assets/modal_success.svg';
import nutritionSvg from '../../../public/assets/nutrition.svg';
import parentPageArrowSvg from '../../../public/assets/parent_page_arrow.svg';
import personalCareSvg from '../../../public/assets/personal_care.svg';
import pharmacySvg from '../../../public/assets/pharmacy.svg';
import pintrestSvg from '../../../public/assets/pintrest_white.svg';
import planDocumentsSvg from '../../../public/assets/plan_documents.svg';
import prescriptionSvg from '../../../public/assets/prescription.svg';
import transportationSvg from '../../../public/assets/primary_transportation.svg';
import primaryVisionSvg from '../../../public/assets/primary_vision.svg';
import priorAuthorizationsSvg from '../../../public/assets/prior_authorizations.svg';
import profileWhiteSvg from '../../../public/assets/profile_white.svg';
import questSelectSvg from '../../../public/assets/quest_select.svg';
import envelopeSvg from '../../../public/assets/request_printed_documents.svg';
import rightSvg from '../../../public/assets/right.svg';
import searchSvg from '../../../public/assets/search.svg';
import searchCareSvg from '../../../public/assets/search_care.svg';
import searchPharmacySvg from '../../../public/assets/search_pharmacy.svg';
import securitySvg from '../../../public/assets/security.svg';
import sharePermissionsSvg from '../../../public/assets/share_permissions.svg';
import shoppingCreditSvg from '../../../public/assets/shopping_credit.svg';
import signoutSvg from '../../../public/assets/signout.svg';
import silverFitSvg from '../../../public/assets/silver_fit.svg';
import spendingAccountsSvg from '../../../public/assets/spending_accounts.svg';
import spendingSummarySvg from '../../../public/assets/spending_summary.svg';
import successIconSvg from '../../../public/assets/success.svg';
import switchFilterIconSvg from '../../../public/assets/switch_filter.svg';
import teladocHealthSVG from '../../../public/assets/teladoc_health.svg';
import upSvg from '../../../public/assets/up.svg';
import upGraySvg from '../../../public/assets/up_gray.svg';
import visionSvg from '../../../public/assets/vision.svg';
import wellnessPointsIconSvg from '../../../public/assets/wellness_points.svg';
import wellTunedBlogSvg from '../../../public/assets/welltuned_blog.svg';
import xSvg from '../../../public/assets/x_white.svg';
import youtubeSvg from '../../../public/assets/youtube_white.svg';

export const bcbstBlueLogo = bcbstLogoSvg;
export const leftIcon = leftIconSvg;
export const closeIcon = closeIconSvg;
export const bcbstSilhouletteLogo = blueCrossSilhouletteSvg;
export const successIcon = successIconSvg;
export const accessGranted = accessGrantedSvg;
export const documentFile = documentFileSvg;
export const connectAccountsIcon = connectAccountssvg;
export const sharePermissionsIcon = sharePermissionsSvg;
export const securityIcon = securitySvg;
export const communicationSettingsIcon = communicationSettingsSvg;
export const parentPageArrowIcon = parentPageArrowSvg;
export const signoutSvgIcon = signoutSvg;
export const switchFilterIcon = switchFilterIconSvg;
export const checkBlueIcon = checkBlueIconSvg;
export const modalAlertIcon = modalAlertSvg;
export const enrollment = enrollmentSvg;
export const claimsBenefitsCoverage = claimsBenefitsCoverageSvg;
export const planDocuments = planDocumentsSvg;
export const priorAuthorizations = priorAuthorizationsSvg;
export const spendingAccounts = spendingAccountsSvg;
export const spendingSummary = spendingSummarySvg;
export const globalIdCardIcon = globalIdCardSvg;
export const inboxIcon = inboxSvg;
export const profileWhiteIcon = profileWhiteSvg;
export const searchIcon = searchSvg;
export const downIcon = downSvg;
export const bcbstStackedlogo = bcbstStackedSvg;
export const externalIcon = externalSvg;
export const hamburgerMenuIcon = hamburgerMenuSvg;
export const upIcon = upSvg;
export const rightIcon = rightSvg;
export const extrenalIcon = externalSvg;
export const alertErrorIcon = alertErrorSvg;
export const externalOffsiteWhiteIcon = externaloffsitewhiteSvg;
export const alertBlueIcon = alertBlueSvg;
export const showPasswordIcon = showPasswordSvg;
export const showPasswordSelectedIcon = showPasswordSelectedSvg;
export const downloadIcon = downloadIconSvg;
export const benefits = benefitsSvg;
export const medicalIcon = medicalSvg;
export const dentalIcon = dentalSvg;
export const pharmacyIcon = pharmacySvg;
export const visionIcon = visionSvg;
export const basicAccessIcon = basicAccess;
export const alightIcon = alightSvg;
export const silverFitLogo = silverFitSvg;
export const teladocHealthLogo = teladocHealthSVG;
export const hingeHealthLogo = hingeHealthSVG;
export const questSelectLogo = questSelectSvg;
export const emailIcon = emailSvg;
export const chatIcon = chatSvg;
export const callIcon = callSvg;
export const questionsIcon = questionsSvg;
export const glossaryIcon = glossarySvg;
export const findFormIcon = findFormSvg;
export const amplifyHealthAppPromoImg = amplifyHealthAppPromo;
export const appleStoreLogo = appleStoreSvg;
export const playStoreLogo = playStoreSvg;
export const healthAssessmentIcon = healthAssessmentIconSvg;
export const interactiveProgramsIcon = interactiveProgramsIconSvg;
export const wellnessPointsIcon = wellnessPointsIconSvg;
export const dentalHealthLibraryIcon = dentalHealthLibrarySvg;
export const wellTunedBlogIcon = wellTunedBlogSvg;
export const biometricScreeningIcon = biometricScreeningSvg;
export const cvsCaremarkIcon = cvsCaremarkSvg;
export const costIcon = costSvg;
export const mailOrderPharmacyIcon = mailOrderPharmacySvg;
export const prescriptionIcon = prescriptionSvg;
export const searchPharmacyIcon = searchPharmacySvg;
export const shoppingCreditIcon = shoppingCreditSvg;
export const idCardPrimaryIconSvg = idCardPrimarySvg;
export const prescription = prescriptionSvg;
export const keyIcon = keySvg;
export const checkGreenIcon = checkGreenSvg;
export const viewMoreIcon = viewMoreSvg;
export const viewLessIcon = viewLessSvg;
export const envelopeIcon = envelopeSvg;
export const ableToLogo = ableToSvg;
export const calenderIcon = calenderSvg;
export const searchCareLogo = searchCareSvg;
export const downGrayIcon = downGraySvg;
export const upGrayIcon = upGraySvg;
export const dollarGeneralLogo = dollarGeneralSvg;
export const fitnessLogo = fitnessSvg;
export const fitLogo = fitSvg;
export const personalCareLogo = personalCareSvg;
export const primaryVisionLogo = primaryVisionSvg;
export const nutritionLogo = nutritionSvg;
export const transportationLogo = transportationSvg;
export const facebookLogo = facebookSvg;
export const linkedinLogo = linkedInSvg;
export const instagramLogo = instagramSvg;
export const youtubeLogo = youtubeSvg;
export const pintrestLogo = pintrestSvg;
export const xLogo = xSvg;
export const bcbstnLogo = bcbstnSvg;
