import alertBlueSvg from '@/../public/assets/Alert-blue.svg';
import showPasswordSelectedSvg from '@/../public/assets/Show-Password-Selected.svg';
import showPasswordSvg from '@/../public/assets/Show-Password.svg';
import amplifyHealthAppPromo from '@/public/assets/AmplifyHealth-App.png';
import appleStoreSvg from '@/public/assets/Apple-Store-2022.svg';
import callSvg from '@/public/assets/call.svg';
import chatSvg from '@/public/assets/chat.svg';
import checkGreenSvg from '@/public/assets/check_green.svg';
import emailSvg from '@/public/assets/email.svg';
import findFormSvg from '@/public/assets/find_form.svg';
import glossarySvg from '@/public/assets/glossary.svg';
import playStoreSvg from '@/public/assets/Google-Play-2022.svg';
import questionsSvg from '@/public/assets/questions.svg';
import viewLessSvg from '@/public/assets/view_less.svg';
import viewMoreSvg from '@/public/assets/view_more.svg';
import ableToSvg from '../../../public/assets/ableTo.svg';
import accessGrantedSvg from '../../../public/assets/Access-Granted.svg';
import alertErrorSvg from '../../../public/assets/Alert-ErrorRed.svg';
import alightSvg from '../../../public/assets/alight.svg';
import bcbstLogoSvg from '../../../public/assets/BCBST-Blue.svg';
import benefitsSvg from '../../../public/assets/benefits.svg';
import biometricScreeningSvg from '../../../public/assets/biometric_screening.svg';
import bcbstStackedSvg from '../../../public/assets/BlueCross-Stacked.svg';
import blueCrossSilhouletteSvg from '../../../public/assets/blueCrossSilhouette.svg';
import calenderSvg from '../../../public/assets/calendar.svg';
import checkBlueIconSvg from '../../../public/assets/check.svg';
import claimsBenefitsCoverageSvg from '../../../public/assets/Claims.svg';
import closeIconSvg from '../../../public/assets/close.svg';
import communicationSettingsSvg from '../../../public/assets/Communication-Settings.svg';
import connectAccountssvg from '../../../public/assets/Connect-Accounts.svg';
import costSvg from '../../../public/assets/cost.svg';
import cvsCaremarkSvg from '../../../public/assets/cvs_caremark.svg';
import dentalSvg from '../../../public/assets/dental.svg';
import dentalHealthLibrarySvg from '../../../public/assets/dental_health_library.svg';
import documentFileSvg from '../../../public/assets/Document-File.svg';
import downSvg from '../../../public/assets/down.svg';
import downGraySvg from '../../../public/assets/down_gray.svg';
import downloadIconSvg from '../../../public/assets/Download.svg';
import enrollmentSvg from '../../../public/assets/enrollment.svg';
import externaloffsitewhiteSvg from '../../../public/assets/External-White.svg';
import { default as externalSvg } from '../../../public/assets/external.svg';
import globalIdCardSvg from '../../../public/assets/global_id_card.svg';
import hamburgerMenuSvg from '../../../public/assets/Hamburger-Menu.svg';
import healthAssessmentIconSvg from '../../../public/assets/health_assessment.svg';
import hingeHealthSVG from '../../../public/assets/hinge_health.svg';
import idCardPrimarySvg from '../../../public/assets/id_card.svg';
import inboxSvg from '../../../public/assets/Inbox.svg';
import interactiveProgramsIconSvg from '../../../public/assets/interactive_programs.svg';
import keySvg from '../../../public/assets/key.svg';
import leftIconSvg from '../../../public/assets/left.svg';
import mailOrderPharmacySvg from '../../../public/assets/mail_order_pharmacy.svg';
import medicalSvg from '../../../public/assets/medical.svg';
import modalAlertSvg from '../../../public/assets/Modal-Alert.svg';
import basicAccess from '../../../public/assets/Modal-Success.svg';
import parentPageArrowSvg from '../../../public/assets/Parent-Page-Arrow.svg';
import pharmacySvg from '../../../public/assets/pharmacy.svg';
import planDocumentsSvg from '../../../public/assets/Plan-Documents.svg';
import prescriptionSvg from '../../../public/assets/prescription.svg';
import priorAuthorizationsSvg from '../../../public/assets/Prior-Authorizations.svg';
import profileWhiteSvg from '../../../public/assets/Profile-White.svg';
import questSelectSvg from '../../../public/assets/quest_select.svg';
import envelopeSvg from '../../../public/assets/request_printed_documents.svg';
import rightSvg from '../../../public/assets/right.svg';
import searchSvg from '../../../public/assets/Search.svg';
import searchPharmacySvg from '../../../public/assets/search_pharmacy.svg';
import securitySvg from '../../../public/assets/Security.svg';
import sharePermissionsSvg from '../../../public/assets/Share-Permissions.svg';
import shoppingCreditSvg from '../../../public/assets/shopping_credit.svg';
import signoutSvg from '../../../public/assets/Signout.svg';
import silverFitSvg from '../../../public/assets/silver_fit.svg';
import spendingAccountsSvg from '../../../public/assets/Spending-Accounts.svg';
import spendingSummarySvg from '../../../public/assets/Spending-Summary.svg';
import successIconSvg from '../../../public/assets/success.svg';
import switchFilterIconSvg from '../../../public/assets/switch-filter.svg';
import teladocHealthSVG from '../../../public/assets/teladoc_health.svg';
import upSvg from '../../../public/assets/up.svg';
import upGraySvg from '../../../public/assets/up_gray.svg';
import visionSvg from '../../../public/assets/vision.svg';
import wellnessPointsIconSvg from '../../../public/assets/wellness_points.svg';
import wellTunedBlogSvg from '../../../public/assets/welltuned_blog.svg';

export const bcbstBlueLogo = bcbstLogoSvg;
export const leftIcon = leftIconSvg;
export const closeIcon = closeIconSvg;
export const bcbstSilhouletteLogo = blueCrossSilhouletteSvg;
export const successIcon = successIconSvg;
export const accessGranted = accessGrantedSvg;
export const documentFile = documentFileSvg;
export const connectAccountsIcon = connectAccountssvg;
export const sharePermissionsIcon = sharePermissionsSvg;
export const securityIcon = securitySvg;
export const communicationSettingsIcon = communicationSettingsSvg;
export const parentPageArrowIcon = parentPageArrowSvg;
export const signoutSvgIcon = signoutSvg;
export const switchFilterIcon = switchFilterIconSvg;
export const checkBlueIcon = checkBlueIconSvg;
export const modalAlertIcon = modalAlertSvg;
export const enrollment = enrollmentSvg;
export const claimsBenefitsCoverage = claimsBenefitsCoverageSvg;
export const planDocuments = planDocumentsSvg;
export const priorAuthorizations = priorAuthorizationsSvg;
export const spendingAccounts = spendingAccountsSvg;
export const spendingSummary = spendingSummarySvg;
export const globalIdCardIcon = globalIdCardSvg;
export const inboxIcon = inboxSvg;
export const profileWhiteIcon = profileWhiteSvg;
export const searchIcon = searchSvg;
export const downIcon = downSvg;
export const bcbstStackedlogo = bcbstStackedSvg;
export const externalIcon = externalSvg;
export const hamburgerMenuIcon = hamburgerMenuSvg;
export const upIcon = upSvg;
export const rightIcon = rightSvg;
export const extrenalIcon = externalSvg;
export const alertErrorIcon = alertErrorSvg;
export const externalOffsiteWhiteIcon = externaloffsitewhiteSvg;
export const alertBlueIcon = alertBlueSvg;
export const showPasswordIcon = showPasswordSvg;
export const showPasswordSelectedIcon = showPasswordSelectedSvg;
export const downloadIcon = downloadIconSvg;
export const benefits = benefitsSvg;
export const medicalIcon = medicalSvg;
export const dentalIcon = dentalSvg;
export const pharmacyIcon = pharmacySvg;
export const visionIcon = visionSvg;
export const basicAccessIcon = basicAccess;
export const alightIcon = alightSvg;
export const silverFitLogo = silverFitSvg;
export const teladocHealthLogo = teladocHealthSVG;
export const hingeHealthLogo = hingeHealthSVG;
export const questSelectLogo = questSelectSvg;
export const emailIcon = emailSvg;
export const chatIcon = chatSvg;
export const callIcon = callSvg;
export const questionsIcon = questionsSvg;
export const glossaryIcon = glossarySvg;
export const findFormIcon = findFormSvg;
export const amplifyHealthAppPromoImg = amplifyHealthAppPromo;
export const appleStoreLogo = appleStoreSvg;
export const playStoreLogo = playStoreSvg;
export const healthAssessmentIcon = healthAssessmentIconSvg;
export const interactiveProgramsIcon = interactiveProgramsIconSvg;
export const wellnessPointsIcon = wellnessPointsIconSvg;
export const dentalHealthLibraryIcon = dentalHealthLibrarySvg;
export const wellTunedBlogIcon = wellTunedBlogSvg;
export const biometricScreeningIcon = biometricScreeningSvg;
export const cvsCaremarkIcon = cvsCaremarkSvg;
export const costIcon = costSvg;
export const mailOrderPharmacyIcon = mailOrderPharmacySvg;
export const prescriptionIcon = prescriptionSvg;
export const searchPharmacyIcon = searchPharmacySvg;
export const shoppingCreditIcon = shoppingCreditSvg;
export const idCardPrimaryIconSvg = idCardPrimarySvg;
export const prescription = prescriptionSvg;
export const keyIcon = keySvg;
export const checkGreenIcon = checkGreenSvg;
export const viewMoreIcon = viewMoreSvg;
export const viewLessIcon = viewLessSvg;
export const envelopeIcon = envelopeSvg;
export const ableToLogo = ableToSvg;
export const calenderIcon = calenderSvg;
export const downGrayIcon = downGraySvg;
export const upGrayIcon = upGraySvg;
