import alertBlueSvg from '@/../public/assets/Alert-blue.svg';
import showPasswordSelectedSvg from '@/../public/assets/Show-Password-Selected.svg';
import showPasswordSvg from '@/../public/assets/Show-Password.svg';
import accessGrantedSvg from '../../../public/assets/Access-Granted.svg';
import alertErrorSvg from '../../../public/assets/Alert-ErrorRed.svg';
import bcbstLogoSvg from '../../../public/assets/BCBST-Blue.svg';
import benefitsCoverageSvg from '../../../public/assets/Benefits-Coverage.svg';
import biometricScreeningSvg from '../../../public/assets/biometric_screening.svg';
import bcbstStackedSvg from '../../../public/assets/BlueCross-Stacked.svg';
import blueCrossSilhouletteSvg from '../../../public/assets/blueCrossSilhouette.svg';
import checkBlueIconSvg from '../../../public/assets/check.svg';
import claimsBenefitsCoverageSvg from '../../../public/assets/Claims.svg';
import closeIconSvg from '../../../public/assets/close.svg';
import communicationSettingsSvg from '../../../public/assets/Communication-Settings.svg';
import connectAccountssvg from '../../../public/assets/Connect-Accounts.svg';
import dentalSvg from '../../../public/assets/dental.svg';
import dentalHealthLibrarySvg from '../../../public/assets/dental_health_library.svg';
import documentFileSvg from '../../../public/assets/Document-File.svg';
import downSvg from '../../../public/assets/down.svg';
import downloadIconSvg from '../../../public/assets/Download.svg';
import externaloffsitewhiteSvg from '../../../public/assets/External-White.svg';
import {
  default as externalSvg,
  default as extrenalSvg,
} from '../../../public/assets/external.svg';
import hamburgerMenuSvg from '../../../public/assets/Hamburger-Menu.svg';
import healthAssessmentIconSvg from '../../../public/assets/health_assessment.svg';
import idCardSvg from '../../../public/assets/ID-Card.svg';
import inboxSvg from '../../../public/assets/Inbox.svg';
import interactiveProgramsIconSvg from '../../../public/assets/interactive_programs.svg';
import leftIconSvg from '../../../public/assets/left.svg';
import medicalSvg from '../../../public/assets/medical.svg';
import modalAlertSvg from '../../../public/assets/Modal-Alert.svg';
import basicAccess from '../../../public/assets/Modal-Success.svg';
import parentPageArrowSvg from '../../../public/assets/Parent-Page-Arrow.svg';
import pharmacySvg from '../../../public/assets/pharmacy.svg';
import planDocumentsSvg from '../../../public/assets/Plan-Documents.svg';
import priorAuthorizationsSvg from '../../../public/assets/Prior-Authorizations.svg';
import profileWhiteSvg from '../../../public/assets/Profile-White.svg';
import rightSvg from '../../../public/assets/right.svg';
import searchSvg from '../../../public/assets/Search.svg';
import securitySvg from '../../../public/assets/Security.svg';
import sharePermissionsSvg from '../../../public/assets/Share-Permissions.svg';
import signoutSvg from '../../../public/assets/Signout.svg';
import spendingAccountsSvg from '../../../public/assets/Spending-Accounts.svg';
import spendingSummarySvg from '../../../public/assets/Spending-Summary.svg';
import successIconSvg from '../../../public/assets/success.svg';
import switchFilterIconSvg from '../../../public/assets/switch-filter.svg';
import upSvg from '../../../public/assets/up.svg';
import visionSvg from '../../../public/assets/vision.svg';
import wellnessPointsIconSvg from '../../../public/assets/wellness_points.svg';
import wellTunedBlogSvg from '../../../public/assets/welltuned_blog.svg';

export const bcbstBlueLogo = bcbstLogoSvg;
export const leftIcon = leftIconSvg;
export const closeIcon = closeIconSvg;
export const bcbstSilhouletteLogo = blueCrossSilhouletteSvg;
export const successIcon = successIconSvg;
export const accessGranted = accessGrantedSvg;
export const documentFile = documentFileSvg;
export const connectAccountsIcon = connectAccountssvg;
export const sharePermissionsIcon = sharePermissionsSvg;
export const securityIcon = securitySvg;
export const communicationSettingsIcon = communicationSettingsSvg;
export const parentPageArrowIcon = parentPageArrowSvg;
export const signoutSvgIcon = signoutSvg;
export const switchFilterIcon = switchFilterIconSvg;
export const checkBlueIcon = checkBlueIconSvg;
export const modalAlertIcon = modalAlertSvg;
export const benefitsCoverage = benefitsCoverageSvg;
export const claimsBenefitsCoverage = claimsBenefitsCoverageSvg;
export const planDocuments = planDocumentsSvg;
export const priorAuthorizations = priorAuthorizationsSvg;
export const spendingAccounts = spendingAccountsSvg;
export const spendingSummary = spendingSummarySvg;
export const idCardIcon = idCardSvg;
export const inboxIcon = inboxSvg;
export const profileWhiteIcon = profileWhiteSvg;
export const searchIcon = searchSvg;
export const downIcon = downSvg;
export const bcbstStackedlogo = bcbstStackedSvg;
export const externalIcon = externalSvg;
export const hamburgerMenuIcon = hamburgerMenuSvg;
export const upIcon = upSvg;
export const rightIcon = rightSvg;
export const extrenalIcon = extrenalSvg;
export const alertErrorIcon = alertErrorSvg;
export const externalOffsiteWhiteIcon = externaloffsitewhiteSvg;
export const alertBlueIcon = alertBlueSvg;
export const showPasswordIcon = showPasswordSvg;
export const showPasswordSelectedIcon = showPasswordSelectedSvg;
export const downloadIcon = downloadIconSvg;
export const medicalIcon = medicalSvg;
export const dentalIcon = dentalSvg;
export const pharmacyIcon = pharmacySvg;
export const visionIcon = visionSvg;
export const basicAccessIcon = basicAccess;
export const healthAssessmentIcon = healthAssessmentIconSvg;
export const interactiveProgramsIcon = interactiveProgramsIconSvg;
export const wellnessPointsIcon = wellnessPointsIconSvg;
export const dentalHealthLibraryIcon = dentalHealthLibrarySvg;
export const wellTunedBlogIcon = wellTunedBlogSvg;
export const biometricScreeningIcon = biometricScreeningSvg;
