export const chrisHallClaims = {
  data: {
    claims: [
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1725336000000,
        claimId: 'EXT820200100',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1725336000000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1728878400000,
        claimPatientOweAmt: 100,
        claimRecievedDate: 1725508800000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'D',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 91722407,
        providerId: '4165326',
        providerName: 'Bhushan, Susan D.',
        providerSpecialty: 'INTM',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMgY62pHR0eHJeqBxqIDd%2FxsUWFYu1in%2FLqrXwR2tGI%2Fni1%2FjiW4s6UiHlVJ5zRqytKpn%2FD9LjO%2BI%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 164.08,
        providerBillingTIN: '621508884',
        payToProviderAddress1: 'PO Box 1030',
        payToProviderCity: 'Chattanooga',
        payToProviderState: 'TN',
        payToProviderZip: '374011030',
        patientAccNo: '6474367',
        vndAmtPaid: 0,
        providerType: 'ITA1',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '09-03-2024',
        claimLowServiceCalendarDate: '09-03-2024',
        claimPaidCalendarDate: '10-14-2024',
        claimReceivedCalendarDate: '09-05-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1722916800000,
        claimId: 'EXT820200200',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1722916800000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1728878400000,
        claimPatientOweAmt: 50,
        claimRecievedDate: 1725508800000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'D',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '0119605',
        providerName: 'Warren County Health Dept',
        providerSpecialty: 'PMPH',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMgY62pHR0eHJ%2BDU6sDozLMQrobCUP6tnsDeHiDIO14NhPxhSxZolZ0DEN%2Bfy81HgEdGFNlIR7SuM%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 83.45,
        providerBillingTIN: '626001445',
        payToProviderAddress1: '1100 England Dr',
        payToProviderCity: 'Cookeville',
        payToProviderState: 'TN',
        payToProviderZip: '38501',
        patientAccNo: 'P1068230040',
        vndAmtPaid: 0,
        providerType: 'ITBM',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '08-06-2024',
        claimLowServiceCalendarDate: '08-06-2024',
        claimPaidCalendarDate: '10-14-2024',
        claimReceivedCalendarDate: '09-05-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1725422400000,
        claimId: 'EXT820200400',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1725422400000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1728878400000,
        claimPatientOweAmt: 65,
        claimRecievedDate: 1725508800000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '4165326',
        providerName: 'Bhushan, Susan D.',
        providerSpecialty: 'INTM',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMgY62pHR0eHLfVJa6gaT2tacruM%2BF4P18f12ccH0qx9nImg%2B4XNI2SjLhmhWtgz04kfqTRJtdP%2Fo%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 111.22,
        providerBillingTIN: '621508884',
        payToProviderAddress1: 'PO Box 1030',
        payToProviderCity: 'Chattanooga',
        payToProviderState: 'TN',
        payToProviderZip: '374011030',
        patientAccNo: '6589693',
        vndAmtPaid: 0,
        providerType: 'ITA1',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '09-04-2024',
        claimLowServiceCalendarDate: '09-04-2024',
        claimPaidCalendarDate: '10-14-2024',
        claimReceivedCalendarDate: '09-05-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728446400000,
        claimId: 'GDCTST300000',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1728446400000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '6272426',
        providerName: 'Rickertsen, Reece N.',
        providerSpecialty: 'PFAY',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeI2KaF9Qp%2BaV%2FeTTqYEXUvYqUSoIMdUsuSjQaULO29f5KJbNimAfuC%2Bk%2BDPEU%2FwUSM%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 298.41,
        providerBillingTIN: '620864163',
        payToProviderAddress1: 'PO Box 7006',
        payToProviderCity: 'Murfreesboro',
        payToProviderState: 'TN',
        payToProviderZip: '371337006',
        patientAccNo: '0289746MMC0475422',
        vndAmtPaid: 0,
        providerType: 'ITA2',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-09-2024',
        claimLowServiceCalendarDate: '10-09-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728100800000,
        claimId: 'GDCTST300100',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1728100800000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '4128532',
        providerName: 'Welch, Derek C.',
        providerSpecialty: 'ACPA',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeLI8HtZxNrNw%2FrpqbRmHZcLvospaZYp1D2HNII%2BtPIalowo6GFSLwddgkP8LHihbmc%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 258.31,
        providerBillingTIN: '621695507',
        payToProviderAddress1: 'PO Box 639196',
        payToProviderCity: 'Cincinnati',
        payToProviderState: 'OH',
        payToProviderZip: '452639196',
        patientAccNo: '03I81319491-5',
        vndAmtPaid: 0,
        providerType: 'ITA1',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-05-2024',
        claimLowServiceCalendarDate: '10-05-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728014400000,
        claimId: 'GDCTST300200',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1727928000000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '6017959',
        providerName: 'Capizzi, Stephen A.',
        providerSpecialty: 'PULD',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeLpJKFamH346xrgNP1prU86otO%2BQy5Ws7XlmYBQ%2B7xF52nx%2Bm5obMdOXGKLLkmgxUU%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 270.26,
        providerBillingTIN: '620874165',
        payToProviderAddress1: 'PO Box 305172 Dept 116',
        payToProviderCity: 'Nashville',
        payToProviderState: 'TN',
        payToProviderZip: '37230-5172',
        patientAccNo: 'MID240170',
        vndAmtPaid: 0,
        providerType: 'ITA1',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-04-2024',
        claimLowServiceCalendarDate: '10-03-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728273600000,
        claimId: 'GDCTST300300',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1728273600000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '5514204',
        providerName: 'Womack, Benjamin D.',
        providerSpecialty: 'INTM',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeJPqqFFRu4EbvJZ3uPcFl9%2F4gyBPuNiNzE%2BLUrZ8MtDLfuyP4Uh4pqXha0dIdiq8OI%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 273.16,
        providerBillingTIN: '352528741',
        payToProviderAddress1: 'Dept A T 40379',
        payToProviderCity: 'Atlanta',
        payToProviderState: 'GA',
        payToProviderZip: '31192',
        patientAccNo: 'P1267008960',
        vndAmtPaid: 0,
        providerType: 'VAMD',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-07-2024',
        claimLowServiceCalendarDate: '10-07-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728014400000,
        claimId: 'GDCTST300400',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1728014400000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '6046545',
        providerName: 'Watson, Melissa I.',
        providerSpecialty: 'NPN3',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeIjE79DPhw32jGsjQJup%2BL6HSnMTn6VvzNcJANjzdlRiiR2jByEggrhNGrziFUkmwQ%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 233.15,
        providerBillingTIN: '452497491',
        payToProviderAddress1: '1211 Dinah Shore Blvd',
        payToProviderCity: 'Winchester',
        payToProviderState: 'TN',
        payToProviderZip: '373981107',
        patientAccNo: '124801Z6161',
        vndAmtPaid: 0,
        providerType: 'ITDF',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-04-2024',
        claimLowServiceCalendarDate: '10-04-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1727582400000,
        claimId: 'GDCTST300500',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1727582400000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '6249284',
        providerName: 'Wade, Joseph F.',
        providerSpecialty: 'SORT',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeICY6ey9EwiTsqrzrJV7zDq7HbmP6yuR4ATrCgWlLgQdG3Wd%2BUVpBQIKzWfqikrevQ%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 331.2,
        providerBillingTIN: '620862316',
        payToProviderAddress1: 'PO Box 9118',
        payToProviderCity: 'Minneapolis',
        payToProviderState: 'MN',
        payToProviderZip: '554809118',
        patientAccNo: '000122311558',
        vndAmtPaid: 0,
        providerType: 'ITA1',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '09-29-2024',
        claimLowServiceCalendarDate: '09-29-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728100800000,
        claimId: 'GDCTST300600',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1728100800000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: -6847786800000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '11',
        claimStatusDescription: 'Awaiting Processing',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '0054438',
        providerName: 'Tomichek, Richard C.',
        providerSpecialty: 'ANES',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeLjO4oYIIv7LnHSOT3L8wFXOfAA4uQahlk2FywOccJDgXjQjXbbaEEXt9KgVP9nTlI%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 0,
        providerBillingTIN: '621184496',
        payToProviderAddress1: 'PO Box 277599',
        payToProviderCity: 'Atlanta',
        payToProviderState: 'GA',
        payToProviderZip: '303847599',
        patientAccNo: '609363',
        vndAmtPaid: 0,
        providerType: 'ITA1',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-05-2024',
        claimLowServiceCalendarDate: '10-05-2024',
        claimPaidCalendarDate: '01-01-1753',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728705600000,
        claimId: 'GDCTST300700',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1728705600000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '6297019',
        providerName: 'Stevens, Ashley',
        providerSpecialty: 'NPAC',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeL4ArU6bsNc8EsyGOJMKoY94yekBGCmGJHMbEZZhsk%2B85ELYU%2F55UwE9XFkhrW%2FNP0%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 258.05,
        providerBillingTIN: '621184496',
        payToProviderAddress1: 'PO Box 277599',
        payToProviderCity: 'Atlanta',
        payToProviderState: 'GA',
        payToProviderZip: '303847588',
        patientAccNo: '652202',
        vndAmtPaid: 0,
        providerType: 'ITDF',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-12-2024',
        claimLowServiceCalendarDate: '10-12-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728273600000,
        claimId: 'GDCTST300800',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1728273600000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '6198528',
        providerName: 'Marlow, Austin B.',
        providerSpecialty: 'PASX',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeIaNzZd5Ipcr2xCRkVOh1VHgDiTwnroFp4Q0%2FK%2Fwdc6ZLTCIhb4gXqtEZ9qbF16dXI%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 240.84,
        providerBillingTIN: '272439479',
        payToProviderAddress1: '155 Covey Dr Ste 100',
        payToProviderCity: 'Franklin',
        payToProviderState: 'TN',
        payToProviderZip: '370676019',
        patientAccNo: '417263021',
        vndAmtPaid: 0,
        providerType: 'ITAR',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-07-2024',
        claimLowServiceCalendarDate: '10-07-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
      {
        claimBenefitAmt: 0,
        claimCOBAmt: 0,
        claimCoInsAmt: 0,
        claimCopayAmt: 0,
        claimDeductibleAmt: 0,
        claimHRAIndicator: 'N',
        claimHighServiceDate: 1728532800000,
        claimId: 'GDCTST300900',
        relatedClaimId: '',
        claimIdAdjustedFrom: '',
        claimIdAdjustedTo: '',
        claimIdCreatedFrom: '',
        claimLowServiceDate: 1728532800000,
        claimNonCoveredAmt: 0,
        networkSavings: 0,
        claimPaidAmt: 0,
        claimPaidDate: 1731387600000,
        claimPatientOweAmt: 0,
        claimRecievedDate: 1728705600000,
        claimStatusCode: '02',
        claimStatusDescription: 'Completed',
        claimSubType: 'M',
        claimTotalChargeAmt: 0,
        claimType: 'M',
        hraClaimPaidAmount: 0,
        bcbstPaysYou: 0,
        memberCk: 877944401,
        providerId: '4036652',
        providerName: 'Rigtrup, Kevin M.',
        providerSpecialty: 'INTM',
        cryptedKeyForEOB:
          'wyyTBm2LiQn4Z7FJZy%2F%2FT%2BTersIabnTMTTfUUGvsaeK9vQ13HArC9W14YHh2ZwG2StdeHj%2FtfPQD%2FTWakNVR2xaIRAXTssE7jVS%2FvI%2BUI8M%3D',
        networkID: '',
        networkSummary: '',
        tierDescription: '',
        tierId: '',
        tierPrefix: '',
        accountNumber: 0,
        totalAllowedAmt: 117.4,
        providerBillingTIN: '621695310',
        payToProviderAddress1: 'PO Box 406683',
        payToProviderCity: 'Atlanta',
        payToProviderState: 'GA',
        payToProviderZip: '303846683',
        patientAccNo: '9X116537478',
        vndAmtPaid: 0,
        providerType: 'ITA1',
        eobInd: '',
        memberSuffix: 0,
        claimHighServiceCalendarDate: '10-10-2024',
        claimLowServiceCalendarDate: '10-10-2024',
        claimPaidCalendarDate: '11-12-2024',
        claimReceivedCalendarDate: '10-12-2024',
        bcbstpaysYou: 0,
      },
    ],
  },
};
