export enum LoginStatus {
  LOGIN_OK,
  MFA_REQUIRED_ONE_DEVICE,
  MFA_REQUIRED_MULTIPLE_DEVICES,
  VERIFY_EMAIL,
  INVALID_CREDENTIALS,
  VALIDATION_FAILURE,
  ERROR,
  MULTIPLE_LOGIN_ATTEMPTS,
  PASSWORD_RESET_REQUIRED,
  EMAIL_UNIQUENESS,
  REACTIVATION_REQUIRED,
  DUPLICATE_ACCOUNT,
}

export enum SelectMFAStatus {
  OK,
  VALIDATION_FAILURE,
  ERROR,
}

export enum SubmitMFAStatus {
  OTP_OK,
  OTP_INVALID_LIMIT_REACHED,
  VALIDATION_FAILURE,
  GENERIC_OR_INLINE_ERROR,
  PASSWORD_RESET_REQUIRED,
  EMAIL_UNIQUENESS,
  DUPLICATE_ACCOUNT,
}

export enum PasswordResetStatus {
  RESET_OK,
  PREVIOUS_PASSWORD,
  COMMON_PASSWORD,
  DOB_NOT_MATCHED,
  ERROR,
}

export enum EmailUniquenessStatus {
  VERIFY_EMAIL,
  INVALID_EMAIL,
  EMAIL_ALREADY_IN_USE,
  ERROR,
}