export enum HealthProgramType {
  TeladocSecondOption = 'teladocSecondOption',
  SilverFit = 'silverFit',
  TeladocBP = 'teladocBP',
  HingeHealth = 'hingeHealth',
  TeladocHealthDiabetesManagement = 'teladocHealthDiabetesManagement',
  QuestSelect = 'questSelect',
  TeladocMentalHealth = 'teladocMentalHealth',
  TeladocPrimaryCareProvider = 'teladocPrimaryCareProvider ',
  TalkToNurse = 'talkToNurse',
  TeladocHealthGeneralUrgentCare = 'teladocHealthGeneralUrgentCare',
  TeladocHealthDiabetesPrevention = 'teladocHealthDiabetesPrevention',
  AbleTo = 'ableTo',
  HealthyMaternity = 'healthyMaternity',
}
