export enum HealthProgramType {
  TeladocSecondOption = 'TeladocSecondOption',
  SilverFit = 'SilverFit',
  TeladocBP = 'TeladocBP',
  HingeHealth = 'HingeHealth',
  TeladocHealthDiabetesManagement = 'TeladocHealthDiabetesManagement',
  QuestSelect = 'QuestSelect',
  TeladocMentalHealth = 'TeladocMentalHealth',
  TeladocPrimaryCareProvider = 'TeladocPrimaryCareProvider ',
  TalkToNurse = 'TalkToNurse',
  TeladocHealthGeneralUrgentCare = 'TeladocHealthGeneralUrgentCare',
  TeladocHealthDiabetesPrevention = 'TeladocHealthDiabetesPrevention',
  AbleTo = 'AbleTo',
  HealthyMaternity = 'HealthyMaternity',
}
