import ServicesUsedPage from '@/app/benefits/servicesUsed/page';
import { mockedAxios } from '@/tests/__mocks__/axios';
import '@testing-library/jest-dom';
import { fireEvent, render, screen } from '@testing-library/react';

jest.mock('src/auth', () => ({
  auth: jest.fn(() =>
    Promise.resolve({
      user: {
        currUsr: {
          plan: { memCk: '123456789', grpId: '87898', sbsbCk: '654567656' },
        },
      },
    }),
  ),
}));

const renderUI = async () => {
  const page = await ServicesUsedPage();
  return render(page);
};

describe('ServicesUsed', () => {
  it('should render the UI correctly', async () => {
    mockedAxios.get
      // Members data
      .mockResolvedValueOnce({
        data: {
          isActive: true,
          subscriberLoggedIn: true,
          lob: 'REGL',
          groupData: {
            groupID: '100000',
            groupCK: '21908',
            groupName: 'Chris B Hall Enterprises',
            parentGroupID: '100001',
            subGroupID: '0001',
            subGroupCK: 28951,
            subGroupName: 'Chris B Hall Enterprises',
            clientID: 'EI',
            policyType: 'INT',
            groupEIN: '620427913',
          },
          networkPrefix: 'QMI',
          subscriberID: '902218823',
          subscriberCK: '91722400',
          subscriberFirstName: 'CHRIS',
          subscriberLastName: 'HALL',
          subscriberTitle: '',
          subscriberDateOfBirth: '08/06/1959',
          subscriberOriginalEffectiveDate: '01/01/2001',
          members: [
            {
              isActive: true,
              memberOrigEffDt: '06/29/2009',
              memberCk: 91722407,
              firstName: 'CHRISTMAS',
              middleInitial: '',
              lastName: 'HALL',
              title: '',
              memRelation: 'S',
              birthDate: '06/29/2009',
              gender: 'M',
              memberSuffix: 6,
              mailAddressType: 'H',
              workPhone: '',
              otherInsurance: [],
              coverageTypes: [
                {
                  productType: 'M',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'S',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'V',
                  coverageLevel: 'A',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
              ],
              planDetails: [
                {
                  productCategory: 'M',
                  planID: 'MBPX0806',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Blue Network P',
                },
                {
                  productCategory: 'S',
                  planID: 'WSXM0218',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Wellness Plan',
                },
                {
                  productCategory: 'V',
                  planID: 'VEMGN002',
                  effectiveDate: 1546318800000,
                  planStartDate: 1383278400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Vision Blue',
                },
              ],
              inXPermissions: true,
              futureEffective: false,
              loggedIn: false,
              hasSocial: true,
              esipharmacyEligible: true,
            },
            {
              isActive: true,
              memberOrigEffDt: '06/15/2009',
              memberCk: 91722406,
              firstName: 'KRISSY',
              middleInitial: 'C',
              lastName: 'HALL',
              title: '',
              memRelation: 'D',
              birthDate: '06/15/2009',
              gender: 'F',
              memberSuffix: 5,
              mailAddressType: 'H',
              workPhone: '',
              otherInsurance: [],
              coverageTypes: [
                {
                  productType: 'M',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'S',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'V',
                  coverageLevel: 'A',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
              ],
              planDetails: [
                {
                  productCategory: 'M',
                  planID: 'MBPX0806',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Blue Network P',
                },
                {
                  productCategory: 'S',
                  planID: 'WSXM0218',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Wellness Plan',
                },
                {
                  productCategory: 'V',
                  planID: 'VEMGN002',
                  effectiveDate: 1546318800000,
                  planStartDate: 1383278400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Vision Blue',
                },
              ],
              inXPermissions: true,
              futureEffective: false,
              loggedIn: false,
              hasSocial: false,
              esipharmacyEligible: true,
            },
            {
              isActive: true,
              memberOrigEffDt: '05/01/2009',
              memberCk: 91722405,
              firstName: 'CHRISTIAN',
              middleInitial: '',
              lastName: 'HALL',
              title: '',
              memRelation: 'S',
              birthDate: '10/31/2011',
              gender: 'M',
              memberSuffix: 4,
              mailAddressType: 'H',
              workPhone: '',
              otherInsurance: [],
              coverageTypes: [
                {
                  productType: 'M',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'S',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'V',
                  coverageLevel: 'A',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
              ],
              planDetails: [
                {
                  productCategory: 'M',
                  planID: 'MBPX0806',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Blue Network P',
                },
                {
                  productCategory: 'S',
                  planID: 'WSXM0218',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Wellness Plan',
                },
                {
                  productCategory: 'V',
                  planID: 'VEMGN002',
                  effectiveDate: 1546318800000,
                  planStartDate: 1383278400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Vision Blue',
                },
              ],
              inXPermissions: true,
              futureEffective: false,
              loggedIn: false,
              hasSocial: true,
              esipharmacyEligible: true,
            },
            {
              isActive: true,
              memberOrigEffDt: '01/01/2001',
              memberCk: 91722402,
              firstName: 'KRISTY',
              middleInitial: '',
              lastName: 'HALL',
              title: '',
              memRelation: 'W',
              birthDate: '05/17/1971',
              gender: 'F',
              memberSuffix: 1,
              mailAddressType: 'H',
              workPhone: '',
              otherInsurance: [],
              coverageTypes: [
                {
                  productType: 'S',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'V',
                  coverageLevel: 'A',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
              ],
              planDetails: [
                {
                  productCategory: 'S',
                  planID: 'WSXM0218',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Wellness Plan',
                },
                {
                  productCategory: 'V',
                  planID: 'VEMGN002',
                  effectiveDate: 1546318800000,
                  planStartDate: 1383278400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Vision Blue',
                },
              ],
              inXPermissions: true,
              futureEffective: false,
              loggedIn: false,
              hasSocial: true,
              esipharmacyEligible: false,
            },
            {
              isActive: true,
              memberOrigEffDt: '01/01/2001',
              memberCk: 91722401,
              firstName: 'CHRIS',
              middleInitial: 'B',
              lastName: 'HALL',
              title: '',
              memRelation: 'M',
              birthDate: '08/06/1959',
              gender: 'M',
              memberSuffix: 0,
              mailAddressType: 'H',
              workPhone: '1234567890',
              otherInsurance: [],
              coverageTypes: [
                {
                  productType: 'D',
                  coverageLevel: '*',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
                {
                  productType: 'M',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'S',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'V',
                  coverageLevel: 'A',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
              ],
              planDetails: [
                {
                  productCategory: 'D',
                  planID: 'DEHCNY02',
                  effectiveDate: 1509508800000,
                  planStartDate: 1451624400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'DentalBlue Preferred Network',
                },
                {
                  productCategory: 'M',
                  planID: 'MBPX0806',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Blue Network P',
                },
                {
                  productCategory: 'S',
                  planID: 'WSXM0218',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Wellness Plan',
                },
                {
                  productCategory: 'V',
                  planID: 'VEMGN002',
                  effectiveDate: 1546318800000,
                  planStartDate: 1383278400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Vision Blue',
                },
              ],
              inXPermissions: true,
              futureEffective: false,
              loggedIn: true,
              hasSocial: true,
              esipharmacyEligible: true,
            },
            {
              isActive: true,
              memberOrigEffDt: '01/01/2014',
              memberCk: 91722409,
              firstName: 'CHRISTOFF',
              middleInitial: '',
              lastName: 'HALL',
              title: '',
              memRelation: 'S',
              birthDate: '01/01/2000',
              gender: 'M',
              memberSuffix: 8,
              mailAddressType: 'H',
              workPhone: '',
              otherInsurance: [],
              coverageTypes: [
                {
                  productType: 'M',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'S',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'V',
                  coverageLevel: 'A',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
              ],
              planDetails: [
                {
                  productCategory: 'M',
                  planID: 'MBPX0806',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Blue Network P',
                },
                {
                  productCategory: 'S',
                  planID: 'WSXM0218',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Wellness Plan',
                },
                {
                  productCategory: 'V',
                  planID: 'VEMGN002',
                  effectiveDate: 1546318800000,
                  planStartDate: 1383278400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Vision Blue',
                },
              ],
              inXPermissions: true,
              futureEffective: false,
              loggedIn: false,
              hasSocial: false,
              esipharmacyEligible: true,
            },
            {
              isActive: true,
              memberOrigEffDt: '12/11/2006',
              memberCk: 91722408,
              firstName: 'CHRISTO',
              middleInitial: '',
              lastName: 'HALL',
              title: '',
              memRelation: 'S',
              birthDate: '12/11/2006',
              gender: 'M',
              memberSuffix: 7,
              mailAddressType: 'H',
              workPhone: '',
              otherInsurance: [],
              coverageTypes: [
                {
                  productType: 'M',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'S',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'V',
                  coverageLevel: 'A',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
              ],
              planDetails: [
                {
                  productCategory: 'M',
                  planID: 'MBPX0806',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Blue Network P',
                },
                {
                  productCategory: 'S',
                  planID: 'WSXM0218',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Wellness Plan',
                },
                {
                  productCategory: 'V',
                  planID: 'VEMGN002',
                  effectiveDate: 1546318800000,
                  planStartDate: 1383278400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Vision Blue',
                },
              ],
              inXPermissions: true,
              futureEffective: false,
              loggedIn: false,
              hasSocial: true,
              esipharmacyEligible: true,
            },
            {
              isActive: true,
              memberOrigEffDt: '12/11/2006',
              memberCk: 54363201,
              firstName: 'ChrisBalance',
              middleInitial: '',
              lastName: 'HALL',
              title: '',
              memRelation: 'S',
              birthDate: '12/11/2006',
              gender: 'M',
              memberSuffix: 7,
              mailAddressType: 'H',
              workPhone: '',
              otherInsurance: [],
              coverageTypes: [
                {
                  productType: 'M',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'S',
                  coverageLevel: 'A',
                  exchange: false,
                  indvGroupInd: '',
                  pedAdultInd: '',
                },
                {
                  productType: 'V',
                  coverageLevel: 'A',
                  exchange: true,
                  indvGroupInd: 'Group',
                  pedAdultInd: 'Adult',
                },
              ],
              planDetails: [
                {
                  productCategory: 'M',
                  planID: 'MBPX0806',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Blue Network P',
                },
                {
                  productCategory: 'S',
                  planID: 'WSXM0218',
                  effectiveDate: 1546318800000,
                  planStartDate: 1514782800000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Wellness Plan',
                },
                {
                  productCategory: 'V',
                  planID: 'VEMGN002',
                  effectiveDate: 1546318800000,
                  planStartDate: 1383278400000,
                  planClassID: 'PPOA',
                  networkPlanName: 'Vision Blue',
                },
              ],
              inXPermissions: true,
              futureEffective: false,
              loggedIn: false,
              hasSocial: true,
              esipharmacyEligible: true,
            },
          ],
          coverageTypes: [
            {
              productType: 'M',
              coverageLevel: 'A',
              exchange: false,
              indvGroupInd: '',
              pedAdultInd: '',
            },
            {
              productType: 'S',
              coverageLevel: 'A',
              exchange: false,
              indvGroupInd: '',
              pedAdultInd: '',
            },
            {
              productType: 'V',
              coverageLevel: 'A',
              exchange: true,
              indvGroupInd: 'Group',
              pedAdultInd: 'Adult',
            },
            {
              productType: 'D',
              coverageLevel: '*',
              exchange: true,
              indvGroupInd: 'Group',
              pedAdultInd: 'Adult',
            },
          ],
          addresses: [
            {
              type: '1',
              address1: 'TEST BLUE ACCESS',
              address2: '',
              address3: '',
              city: 'Chattanooga',
              state: 'TN',
              zipcode: '37412',
              county: 'HAMILTON',
              phone: '',
              email: '',
            },
            {
              type: '2',
              address1: 'TEST 2 BLUE ACCESS',
              address2: '',
              address3: '',
              city: 'Chattanooga',
              state: 'TN',
              zipcode: '37402',
              county: 'HAMILTON',
              phone: '',
              email: '',
            },
            {
              type: 'H',
              address1: '1 CAMERON HILL CIRCLE',
              address2: '',
              address3: '',
              city: 'CHATTANOOGA',
              state: 'TN',
              zipcode: '37402',
              county: 'HAMILTON',
              phone: '4235353065',
              email: '',
            },
          ],
          healthCareAccounts: [],
          esigroupNum: '100000MBPX0806',
          cmcondition: [],
        },
      })
      // Member Limits
      .mockResolvedValueOnce({
        data: {
          listofOufOfPocketDetails: [
            {
              serviceDesc: '$3,000.00 Out of Pocket - Individual  - In Network',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 600,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 3000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'I',
            },
            {
              serviceDesc:
                '$6,000.00 Out of Pocket - Individual  - Out of Network',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 650,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 6000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'O',
            },
            {
              serviceDesc: '$3,000.00 Out of Pocket - Individual  - In Network',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 600,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 3000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'I',
            },
            {
              serviceDesc:
                '$6,000.00 Out of Pocket - Individual  - Out of Network',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 650,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 6000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'O',
            },
            {
              serviceDesc: '$3,000.00 Out of Pocket - Individual  - In Network',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 600,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 3000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'I',
            },
            {
              serviceDesc:
                '$6,000.00 Out of Pocket - Individual  - Out of Network',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 650,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 6000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'O',
            },
            {
              serviceDesc: '$3,000.00 Out of Pocket - Individual  - In Network',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 600,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 3000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'I',
            },
            {
              serviceDesc:
                '$6,000.00 Out of Pocket - Individual  - Out of Network',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 650,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 6000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'O',
            },
            {
              serviceDesc: '$3,000.00 Out of Pocket - Individual  - In Network',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 600,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 3000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'I',
            },
            {
              serviceDesc:
                '$6,000.00 Out of Pocket - Individual  - Out of Network',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 650,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 6000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'O',
            },
            {
              serviceDesc: '$3,000.00 Out of Pocket - Individual  - In Network',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 600,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 3000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'I',
            },
            {
              serviceDesc:
                '$6,000.00 Out of Pocket - Individual  - Out of Network',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 650,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 6000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: false,
              networkIndicator: 'O',
            },
            {
              serviceDesc: '$6,000.00 Out of Pocket - Family - In Network',
              productId: 'MBPX0708',
              memberCK: 0,
              accumNum: 700,
              policyType: 'M',
              firstName: 'FAMILY',
              lastName: 'FAMILY',
              maxAllowedAmount: 6000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: true,
              networkIndicator: 'I',
            },
            {
              serviceDesc: '$12,000.00 Out of Pocket - Family - Out of Network',
              productId: 'MBPX0708',
              memberCK: 0,
              accumNum: 750,
              policyType: 'M',
              firstName: 'FAMILY',
              lastName: 'FAMILY',
              maxAllowedAmount: 12000,
              metAmount: 0,
              exclusionCreditDays: 0,
              familyIndicator: true,
              networkIndicator: 'O',
            },
          ],
          listofLifeTimeLimitDetails: [],
          listofServiceLimitDetails: [
            {
              serviceDesc: '1 Visit Per Calendar Year -- Mammogram',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 1,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Gyn',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 2,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 2,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '12 Visits Per Year - Dietary Counseling',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 25,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 12,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '4 Injections Per Year --  Trigger Point Injection',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 32,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '20 Per Benefit Period - Urine/Serum Drug Testing',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 38,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 20,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year - Wellcare - Over Age 6',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 300,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 1,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Tobacco Cessation Counseling',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 305,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Alcohol Misuse Counseling',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 340,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc:
                '$10,000 Per Benefit Period - Organ Transplant -Travel, Meals & Lodging',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 380,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 10000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$1,000 Per Benefit Period û General Travel Benefit',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 390,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 1000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$40,000 Lifetime Max - Infertility Treatment',
              productId: 'MBPX0708',
              memberCK: 91722401,
              accumNum: 550,
              policyType: 'M',
              firstName: 'CHRIS          ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 40000,
              metAmount: 0,
              limitPeriodInd: 'L',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Mammogram',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 1,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Gyn',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 2,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 2,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '12 Visits Per Year - Dietary Counseling',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 25,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 12,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '4 Injections Per Year --  Trigger Point Injection',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 32,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '20 Per Benefit Period - Urine/Serum Drug Testing',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 38,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 20,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year - Wellcare - Over Age 6',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 300,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 1,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Tobacco Cessation Counseling',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 305,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Alcohol Misuse Counseling',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 340,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc:
                '$10,000 Per Benefit Period - Organ Transplant -Travel, Meals & Lodging',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 380,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 10000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$1,000 Per Benefit Period û General Travel Benefit',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 390,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 1000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$40,000 Lifetime Max - Infertility Treatment',
              productId: 'MBPX0708',
              memberCK: 91722405,
              accumNum: 550,
              policyType: 'M',
              firstName: 'CHRISTIAN      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 40000,
              metAmount: 0,
              limitPeriodInd: 'L',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Mammogram',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 1,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Gyn',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 2,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 2,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '12 Visits Per Year - Dietary Counseling',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 25,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 12,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '4 Injections Per Year --  Trigger Point Injection',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 32,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '20 Per Benefit Period - Urine/Serum Drug Testing',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 38,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 20,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year - Wellcare - Over Age 6',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 300,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 1,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Tobacco Cessation Counseling',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 305,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Alcohol Misuse Counseling',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 340,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc:
                '$10,000 Per Benefit Period - Organ Transplant -Travel, Meals & Lodging',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 380,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 10000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$1,000 Per Benefit Period û General Travel Benefit',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 390,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 1000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$40,000 Lifetime Max - Infertility Treatment',
              productId: 'MBPX0708',
              memberCK: 91722406,
              accumNum: 550,
              policyType: 'M',
              firstName: 'KRISSY         ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 40000,
              metAmount: 0,
              limitPeriodInd: 'L',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Mammogram',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 1,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Gyn',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 2,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 2,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '12 Visits Per Year - Dietary Counseling',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 25,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 12,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '4 Injections Per Year --  Trigger Point Injection',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 32,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '20 Per Benefit Period - Urine/Serum Drug Testing',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 38,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 20,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year - Wellcare - Over Age 6',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 300,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 1,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Tobacco Cessation Counseling',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 305,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Alcohol Misuse Counseling',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 340,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc:
                '$10,000 Per Benefit Period - Organ Transplant -Travel, Meals & Lodging',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 380,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 10000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$1,000 Per Benefit Period û General Travel Benefit',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 390,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 1000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$40,000 Lifetime Max - Infertility Treatment',
              productId: 'MBPX0708',
              memberCK: 91722407,
              accumNum: 550,
              policyType: 'M',
              firstName: 'CHRISTMAS      ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 40000,
              metAmount: 0,
              limitPeriodInd: 'L',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Mammogram',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 1,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Gyn',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 2,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 2,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '12 Visits Per Year - Dietary Counseling',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 25,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 12,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '4 Injections Per Year --  Trigger Point Injection',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 32,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '20 Per Benefit Period - Urine/Serum Drug Testing',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 38,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 20,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year - Wellcare - Over Age 6',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 300,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 1,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Tobacco Cessation Counseling',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 305,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Alcohol Misuse Counseling',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 340,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc:
                '$10,000 Per Benefit Period - Organ Transplant -Travel, Meals & Lodging',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 380,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 10000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$1,000 Per Benefit Period û General Travel Benefit',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 390,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 1000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$40,000 Lifetime Max - Infertility Treatment',
              productId: 'MBPX0708',
              memberCK: 91722408,
              accumNum: 550,
              policyType: 'M',
              firstName: 'CHRISTO        ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 40000,
              metAmount: 0,
              limitPeriodInd: 'L',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Mammogram',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 1,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year -- Gyn',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 2,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 2,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '12 Visits Per Year - Dietary Counseling',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 25,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 12,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '4 Injections Per Year --  Trigger Point Injection',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 32,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 4,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '20 Per Benefit Period - Urine/Serum Drug Testing',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 38,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 20,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '1 Visit Per Calendar Year - Wellcare - Over Age 6',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 300,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 1,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Tobacco Cessation Counseling',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 305,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc: '8 Visits Per Year - Alcohol Misuse Counseling',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 340,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: false,
              maxAllowedVisits: 8,
              usedVisits: 0,
              days: false,
            },
            {
              serviceDesc:
                '$10,000 Per Benefit Period - Organ Transplant -Travel, Meals & Lodging',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 380,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 10000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$1,000 Per Benefit Period û General Travel Benefit',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 390,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 1000,
              metAmount: 0,
              limitPeriodInd: 'P',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
            {
              serviceDesc: '$40,000 Lifetime Max - Infertility Treatment',
              productId: 'MBPX0708',
              memberCK: 91722409,
              accumNum: 550,
              policyType: 'M',
              firstName: 'CHRISTOF       ',
              lastName: 'HALL                               ',
              maxAllowedAmount: 40000,
              metAmount: 0,
              limitPeriodInd: 'L',
              exclusionCreditDays: 0,
              isDollarLimit: true,
              days: false,
            },
          ],
          isOOPCombined: false,
        },
      });

    const component = await renderUI();
    expect(screen.getByText('Services Used')).toBeVisible();
    expect(
      screen.getByText(
        /Below is a list of common services, the maximum amount covered by your plan and how many you've used./i,
      ),
    ).toBeVisible();
    expect(screen.getByText('Medical Services Used')).toBeVisible();
    expect(
      screen.getByText(
        /Some services have limits on how many are covered. You may still have a cost for them. If you reach maximum, you can still get them, but your plan won't cover them/i,
      ),
    ).toBeVisible();
    expect(
      screen.getByText('1 Visit Per Calendar Year -- Mammogram'),
    ).toBeVisible();

    expect(component).toMatchSnapshot();

    // Change the User to Krissy Hall

    fireEvent.click(screen.getAllByText('CHRISTMAS HALL')[0]);
    fireEvent.click(screen.getByText('KRISTY HALL'));

    // The service used should not show up
    expect(
      screen.queryByText('1 Visit Per Calendar Year -- Mammogram'),
    ).toBeNull();
  });
});
