export enum LoginStatus {
  LOGIN_OK,
  MFA_REQUIRED_ONE_DEVICE,
  MFA_REQUIRED_MULTIPLE_DEVICES,
  VERIFY_EMAIL,
  INVALID_CREDENTIALS,
  VALIDATION_FAILURE,
  ERROR,
  MULTIPLE_LOGIN_ATTEMPTS,
}

export enum SelectMFAStatus {
  OK,
  VALIDATION_FAILURE,
  ERROR,
}

export enum SubmitMFAStatus {
  OTP_OK,
  OTP_INVALID_LIMIT_REACHED,
  VALIDATION_FAILURE,
  GENERIC_OR_INLINE_ERROR,
}
