export enum LoginStatus {
  LOGIN_OK,
  MFA_REQUIRED_ONE_DEVICE,
  MFA_REQUIRED_MULTIPLE_DEVICES,
  VERIFY_EMAIL,
  INVALID_CREDENTIALS,
  VALIDATION_FAILURE,
  ERROR,
}

export enum SelectMFAStatus {
  OK,
  VALIDATION_FAILURE,
  ERROR,
}

export enum SubmitMFAStatus {
  OTP_OK,
  OTP_INVALID,
  VALIDATION_FAILURE,
  ERROR,
}
