export const MedicalBenefitsStub: BenefitDetailsBean = {
  planId: 'MBPX0806',
  productType: 'M',
  planStartDate: '01-01-2018',
  planEffectiveDate: '01-01-2019',
  planTermDate: '',
  coverageLevelCode: 'A',
  coverageLevelDescription: 'Family',
  carveOutInfo: [],
  rateSchedule: [],
  networkTiers: [
    {
      tierID: 'BL1',
      tierDesc: 'Benefit Level 1',
      tierExplanation:
        'Services performed by any Network P provider or facility excluding Methodist and St Francis Facilities',
      netWorkInd: 'I',
      dispOrder: 1,
    },
    {
      tierID: 'BL2',
      tierDesc: 'Benefit Level 2',
      tierExplanation:
        'Services performed by Methodist or St Francis Facilities',
      netWorkInd: 'I',
      dispOrder: 2,
    },
    {
      tierID: 'OON',
      tierDesc: 'Out-of-Network',
      tierExplanation:
        'Services performed by any provider not participating in Blue Network P',
      netWorkInd: 'O',
      dispOrder: 3,
    },
  ],
  serviceCategories: [
    {
      category: 'Preventive Care',
      id: 101,
      comments: '',
    },
    {
      category: 'Office Visits',
      id: 102,
      comments: '',
    },
    {
      category: 'Allergy',
      id: 452,
      comments: '',
    },
    {
      category: 'Emergency',
      id: 103,
      comments: '',
    },
    {
      category: 'Inpatient Services',
      id: 104,
      comments: '',
    },
    {
      category: 'Outpatient Services',
      id: 105,
      comments: '',
    },
    {
      category: 'Medical Equipment/Prosthetics/Orthotics',
      id: 106,
      comments: '',
    },
    {
      category: 'Behavioral Health',
      id: 108,
      comments: '',
    },
    {
      category: 'Other Services',
      id: 109,
      comments: '',
    },
  ],
  coveredServices: [
    {
      serviceDetails: [
        {
          categoryId: 101,
          description: 'Benefit Level 1 Routine Exams In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YREX',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment: 'LIMITED TO 1 VISIT PER BENEFIT PERIOD',
        },
        {
          categoryId: 101,
          description: 'Benefit Level 2 Routine Exams In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VREX',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment: 'LIMITED TO 1 VISIT PER BENEFIT PERIOD',
        },
        {
          categoryId: 101,
          description: 'Routine Exams Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZREX',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description: 'Benefit Level 1 Office Visit, PCP In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YPCP',
          copay: 15.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 452,
          description: 'Benefit Level 1 Office Visit, PCP In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YPCP',
          copay: 15.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Benefit Level 2 Office Visit, PCP In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VPCP',
          copay: 15.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 452,
          description: 'Benefit Level 2 Office Visit, PCP In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VPCP',
          copay: 15.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Office Visit, PCP Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZPCP',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
        {
          categoryId: 452,
          description: 'Office Visit, PCP Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZPCP',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 103,
          description: 'Benefit Level 1 Facility Emergency Room In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YMER',
          copay: 300.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 103,
          description: 'Benefit Level 2 Facility Emergency Room In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VMER',
          copay: 300.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 103,
          description: 'Facility Emergency Room Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZMER',
          copay: 300.0,
          deductible: 1500.0,
          memberPays: 20.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 104,
          description: 'Benefit Level 1 Room & Board In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSRB',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 104,
          description: 'Benefit Level 2 Room & Board In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSRB',
          copay: 100.0,
          deductible: 750.0,
          memberPays: 40.0,
        },
        {
          categoryId: 104,
          description: 'Room & Board Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSRB',
          copay: 300.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 105,
          description: 'Benefit Level 1 Outpatient Surgery Facility In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YOSF',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 105,
          description: 'Benefit Level 2 Outpatient Surgery Facility In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VOSF',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 40.0,
        },
        {
          categoryId: 105,
          description: 'Outpatient Surgery Facility Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZOSF',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 106,
          description: 'Benefit Level 1 Durable Medical Equipment In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YDME',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
          comment:
            'Hearing Aids for members ages 18 and over are limited to one per ear every 3 years with a maximum of $5000',
        },
        {
          categoryId: 106,
          description: 'Benefit Level 2 Durable Medical Equipment In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VDME',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
          comment:
            'Hearing Aids for members ages 18 and over are limited to one per ear every 3 years with a maximum of $5000',
        },
        {
          categoryId: 106,
          description: 'Durable Medical Equipment Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZDME',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 107,
          description:
            'Benefit Level 1 Prescription Drugs, Generic x1 In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YRXG',
          copay: 7.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 107,
          description:
            'Benefit Level 2 Prescription Drugs, Generic x1 In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VRXG',
          copay: 7.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 107,
          description: 'Prescription Drugs, Generic x1 Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZRXG',
          copay: 0.0,
          deductible: 500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 108,
          description:
            'Benefit Level 1 Behavioral Health Room & Board In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSRP',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 108,
          description:
            'Benefit Level 2 Behavioral Health Room & Board In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSRP',
          copay: 100.0,
          deductible: 750.0,
          memberPays: 40.0,
        },
        {
          categoryId: 108,
          description: 'Behavioral Health Room & Board Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSRP',
          copay: 300.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 109,
          description: 'Benefit Level 1 Overall Member Coinsurance In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YCON',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 109,
          description: 'Benefit Level 2 Overall Member Coinsurance In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VCON',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 109,
          description: 'Overall Member Coinsurance Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZCON',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description: 'Benefit Level 1 Office Specialist In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YVO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 452,
          description: 'Benefit Level 1 Office Specialist In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YVO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Benefit Level 2 Office Specialist In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VVO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 452,
          description: 'Benefit Level 2 Office Specialist In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VVO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Office Specialist Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZVO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
        {
          categoryId: 452,
          description: 'Office Specialist Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZVO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 103,
          description:
            'Benefit Level 1 Emergency Physician Services In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YER',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 103,
          description:
            'Benefit Level 2 Emergency Physician Services In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VER',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 103,
          description: 'Emergency Physician Services Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZER',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 20.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 105,
          description:
            'Benefit Level 1 Outpatient Surgery Physician In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSRO',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 105,
          description:
            'Benefit Level 2 Outpatient Surgery Physician In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSRO',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 105,
          description: 'Outpatient Surgery Physician Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSRO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 106,
          description: 'Benefit Level 1 Prosthetics In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YPRO',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 106,
          description: 'Benefit Level 2 Prosthetics In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VPRO',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 106,
          description: 'Prosthetics Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZPRO',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 107,
          description:
            'Benefit Level 1 Prescription Drugs, Preferred Brand x1 In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YRXP',
          copay: 30.0,
          deductible: 250.0,
          memberPays: 0.0,
        },
        {
          categoryId: 107,
          description:
            'Benefit Level 2 Prescription Drugs, Preferred Brand x1 In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VRXP',
          copay: 30.0,
          deductible: 250.0,
          memberPays: 0.0,
        },
        {
          categoryId: 107,
          description: 'Prescription Drugs, Preferred Brand x1 Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZRXP',
          copay: 0.0,
          deductible: 500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 109,
          description: 'Benefit Level 1 Injections In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YINJ',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 109,
          description: 'Benefit Level 2 Injections In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VINJ',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 109,
          description: 'Injections Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZINJ',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 101,
          description: 'Benefit Level 1 Routine Gynecological Exam In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YGYN',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 101,
          description: 'Benefit Level 2 Routine Gynecological Exam In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VGYN',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 101,
          description: 'Routine Gynecological Exam Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZGYN',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description: 'Benefit Level 1 Office Surgery - PCP In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSPS',
          copay: 15.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Benefit Level 2 Office Surgery PCP In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSPS',
          copay: 15.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Office Surgery  PCP Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSPS',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 104,
          description:
            'Benefit Level 1 Maternity Delivery (Inpatient Physician Services) In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YATI',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 104,
          description:
            'Benefit Level 2 Maternity Delivery (Inpatient Physician Services) In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VATI',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 104,
          description:
            'Maternity Delivery (Inpatient Physician Services) Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZATI',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 105,
          description:
            'Benefit Level 1 Maternity Delivery (Outpatient Physician Services) In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YATO',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 105,
          description:
            'Benefit Level 2 Maternity Delivery (Outpatient Physician Services) In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VATO',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 105,
          description:
            'Maternity Delivery (Outpatient Physician Services) Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZATO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 106,
          description: 'Benefit Level 1 Orthotic Devices In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YODT',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 106,
          description: 'Benefit Level 2 Orthotic Devices In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VODT',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 106,
          description: 'Orthotic Devices Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZODT',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 107,
          description:
            'Benefit Level 1 Prescription Drugs, Non-Preferred Brand x1 In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YRX',
          copay: 50.0,
          deductible: 250.0,
          memberPays: 0.0,
        },
        {
          categoryId: 107,
          description:
            'Benefit Level 2 Prescription Drugs, Non-Preferred Brand x1 In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VRX',
          copay: 50.0,
          deductible: 250.0,
          memberPays: 0.0,
        },
        {
          categoryId: 107,
          description:
            'Prescription Drugs, Non-Preferred Brand x1 Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZRX',
          copay: 0.0,
          deductible: 500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 109,
          description: 'Benefit Level 1 TMJ Office In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YTMJ',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 109,
          description: 'Benefit Level 2 TMJ Office In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VTMJ',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 109,
          description: 'TMJ Office Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZTMJ',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 452,
          description: 'Benefit Level 1 Allergy Injection, Office In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YATX',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 452,
          description: 'Benefit Level 2 Allergy Injection, Office In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VATX',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 452,
          description: 'Allergy Injection, Office Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZATX',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 101,
          description: 'Benefit Level 1 Routine Child Care In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YRIC',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 101,
          description: 'Benefit Level 2 Routine Child Care In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VRIC',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 101,
          description: 'Routine Child Care Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZRIC',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description: 'Benefit Level 1 Office Surgery - Specialist In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSSS',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Benefit Level 2 Office Surgery-Specialist In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSSS',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Office Surgery Specialist Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSSS',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 103,
          description: 'Benefit Level 1 Ambulance In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YAMB',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 103,
          description: 'Benefit Level 2 Ambulance In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VAMB',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 103,
          description: 'Ambulance Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZAMB',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 20.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 104,
          description:
            'Benefit Level 1 Advanced Radiological / High Tech Imaging, Inpatient Facility In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YMRI',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
          comment: 'INCLUDES CT SCAN, NUCLEAR MEDICINE, ETC.',
        },
        {
          categoryId: 104,
          description:
            'Benefit Level 2 Advanced Radiological / High Tech Imaging, Inpatient Facility In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VMRI',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 40.0,
          comment: 'INCLUDES CT SCAN, NUCLEAR MEDICINE, ETC.',
        },
        {
          categoryId: 104,
          description:
            'Advanced Radiological / High Tech Imaging, Inpatient Facility Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZMRI',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
          comment: 'INCLUDES CT SCAN, NUCLEAR MEDICINE, ETC.',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 105,
          description:
            'Benefit Level 1 Routine Diagnostic Services, Outpatient Facility In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YFRX',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 105,
          description:
            'Benefit Level 2 Routine Diagnostic Services, Outpatient Facility In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VFRX',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 40.0,
        },
        {
          categoryId: 105,
          description:
            'Routine Diagnostic Services, Outpatient Facility Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZFRX',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 109,
          description: 'Benefit Level 1 Home Health In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YHHH',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
        },
        {
          categoryId: 109,
          description: 'Benefit Level 2 Home Health In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VHHH',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 40.0,
        },
        {
          categoryId: 109,
          description: 'Home Health Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZHHH',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 452,
          description: 'Benefit Level 1 Allergy Testing, Office In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YATE',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 452,
          description: 'Benefit Level 2 Allergy Testing, Office In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VATE',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 452,
          description: 'Allergy Testing, Office Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZATE',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 101,
          description: 'Benefit Level 1 Immunizations In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YIMU',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 101,
          description: 'Benefit Level 2 Immunizations In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VIMU',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 101,
          description: 'Immunizations Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZIMU',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description:
            'Benefit Level 1 Routine Diagnostic Services, Office In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YRDO',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description:
            'Benefit Level 2 Routine Diagnostic Services, Office In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VRDO',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Routine Diagnostic Services, Office Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZRDO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 104,
          description: 'Benefit Level 1 Skilled Nursing Facility In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSNF',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
          comment: 'LIMITED TO 70 DAYS COMBINED WITH REHAB PER BENEFIT PERIOD',
        },
        {
          categoryId: 104,
          description: 'Benefit Level 2 Skilled Nursing Facility In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSNF',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 40.0,
          comment: 'LIMITED TO 70 DAYS COMBINED WITH REHAB PER BENEFIT PERIOD',
        },
        {
          categoryId: 104,
          description: 'Skilled Nursing Facility Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSNF',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
          comment: 'LIMITED TO 70 DAYS COMBINED WITH REHAB PER BENEFIT PERIOD',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 105,
          description:
            'Benefit Level 1 Advanced Radiological / High Tech Imaging, Outpatient Facility In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YFMR',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 20.0,
          comment: 'INCLUDES CT SCAN, NUCLEAR MEDICINE, ETC.',
        },
        {
          categoryId: 105,
          description:
            'Benefit Level 2 Advanced Radiological / High Tech Imaging, Outpatient Facility In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VFMR',
          copay: 0.0,
          deductible: 750.0,
          memberPays: 40.0,
          comment: 'INCLUDES CT SCAN, NUCLEAR MEDICINE, ETC.',
        },
        {
          categoryId: 105,
          description:
            'Advanced Radiological / High Tech Imaging, Outpatient Facility Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZFMR',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
          comment: 'INCLUDES CT SCAN, NUCLEAR MEDICINE, ETC.',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 108,
          description: 'Benefit Level 1 Behavioral Health Physician In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YVPO',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment:
            'THE FIRST TEN (10) BEHAVIORAL HEALTH OFFICE VISITS WILL BE COVERED AT 100% PER BENEFIT PERIOD.  FOR THE REMAINDER OF THE BENEFIT PERIOD, VISITS WILL APPLY A $10 COPAY THEN 100%.',
        },
        {
          categoryId: 108,
          description: 'Benefit Level 2 Behavioral Health Physician In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VVPO',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment:
            'THE FIRST TEN (10) BEHAVIORAL HEALTH OFFICE VISITS WILL BE COVERED AT 100% PER BENEFIT PERIOD.  FOR THE REMAINDER OF THE BENEFIT PERIOD, VISITS WILL APPLY A $10 COPAY THEN 100%.',
        },
        {
          categoryId: 108,
          description: 'Behavioral Health Physician Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZVPO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 105,
          description:
            'Benefit Level 1 Physical Therapy, Outpatient Physician In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YPTO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
        {
          categoryId: 105,
          description:
            'Benefit Level 2 Physical Therapy, Outpatient Physician In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VPTO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
        {
          categoryId: 105,
          description: 'Physical Therapy, Outpatient Physician Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZPTO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 105,
          description:
            'Benefit Level 1 Speech Therapy, Outpatient Physician In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSTO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
        {
          categoryId: 105,
          description:
            'Benefit Level 2 Speech Therapy, Outpatient Physician In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSTO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
        {
          categoryId: 105,
          description: 'Speech Therapy, Outpatient Physician Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSTO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 105,
          description:
            'Benefit Level 1 Occupational Therapy, Outpatient Physician In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YOTO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
        {
          categoryId: 105,
          description:
            'Benefit Level 2 Occupational Therapy, Outpatient Physician In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VOTO',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
        {
          categoryId: 105,
          description:
            'Occupational Therapy, Outpatient Physician Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZOTO',
          copay: 0.0,
          deductible: 1500.0,
          memberPays: 50.0,
          comment:
            'PHYSICAL, OCCUPATIONAL, SPEECH, COGNITIVE AND PULMONARY REHABILITATIVE THERAPIES ARE LIMITED TO 60 VISITS PER BENEFIT PERIOD FOR ALL COMBINED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description:
            'Benefit Level 1 Teladoc Health General Medical In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YTDU',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description:
            'Benefit Level 2 Teladoc Health General Medical In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VTDU',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description:
            'Benefit Level 1 Teladoc Health Mental Health Care In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YTDB',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description:
            'Benefit Level 2 Teladoc Health Mental Health Care In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VTDB',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 109,
          description: 'Benefit Level 1 Vision Exams In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YVEX',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
        {
          categoryId: 109,
          description: 'Benefit Level 2 Vision Exams In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VVEX',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
        {
          categoryId: 109,
          description: 'Vision Exams Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZVEX',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description: 'Benefit Level 1 Teladoc Health Dermatology In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YTDD',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Benefit Level 2 Teladoc Health Dermatology In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VTDD',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 109,
          description: 'Benefit Level 1 Vision/Contacts In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSRC',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
        {
          categoryId: 109,
          description: 'Benefit Level 2 Vision/Contacts In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSRC',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
        {
          categoryId: 109,
          description: 'Vision/Contacts Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSRC',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 109,
          description: 'Benefit Level 1 Vision/Lens In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSRL',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
        {
          categoryId: 109,
          description: 'Benefit Level 2 Vision/Lens In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSRL',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
        {
          categoryId: 109,
          description: 'Vision/Lens Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSRL',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description:
            'Benefit Level 1 Teladoc Health Nutrition Counseling In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YTDN',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description:
            'Benefit Level 2 Teladoc Health Nutrition Counseling In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VTDN',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 109,
          description: 'Benefit Level 1 Vision/Frames In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YSRF',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
        {
          categoryId: 109,
          description: 'Benefit Level 2 Vision/Frames In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VSRF',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
        {
          categoryId: 109,
          description: 'Vision/Frames Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZSRF',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description: 'Benefit Level 1 Chiropractic Manipulation In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YVCM',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment: 'LIMITED TO 20 VISITS PER BENEFIT PERIOD',
        },
        {
          categoryId: 102,
          description: 'Benefit Level 2 Chiropractic Manipulation In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VVCM',
          copay: 30.0,
          deductible: 0.0,
          memberPays: 0.0,
          comment: 'LIMITED TO 20 VISITS PER BENEFIT PERIOD',
        },
        {
          categoryId: 102,
          description: 'Chiropractic Manipulation Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZVCM',
          copay: 0.0,
          deductible: 0.0,
          memberPays: 100.0,
          comment: 'NOT COVERED',
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description: 'Benefit Level 1 Urgent Care, Facility In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YURG',
          copay: 75.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description:
            'Benefit Level 2 In-Network Urgent Care, Facility In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VURG',
          copay: 75.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Urgent Care, Facility Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZURG',
          copay: 75.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
    {
      serviceDetails: [
        {
          categoryId: 102,
          description: 'Benefit Level 1 Urgent Care, Physician In-Network',
          tierCode: 'BL1',
          serviceTypeCode: 'YURP',
          copay: 75.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Benefit Level 2 Urgent Care, Physician In-Network',
          tierCode: 'BL2',
          serviceTypeCode: 'VURP',
          copay: 75.0,
          deductible: 0.0,
          memberPays: 0.0,
        },
        {
          categoryId: 102,
          description: 'Urgent Care, Physician Out-of-Network',
          tierCode: 'OON',
          serviceTypeCode: 'ZURP',
          copay: 75.0,
          deductible: 1500.0,
          memberPays: 50.0,
        },
      ],
    },
  ],
};
