import MyPlanPage from '@/app/myPlan/page';
import { mockedAxios } from '@/tests/__mocks__/axios';
import { mockedFetch } from '@/tests/setup';
import { fetchRespWrapper } from '@/tests/test_utils';
import '@testing-library/jest-dom';
import { render, screen } from '@testing-library/react';

const renderUI = async () => {
  const page = await MyPlanPage();
  return render(page);
};

jest.mock('src/auth', () => ({
  auth: jest.fn(() =>
    Promise.resolve({
      user: {
        currUsr: {
          plan: {
            memCk: '91722407',
            grpId: '100000',
            sbsbCk: '91722400',
          },
        },
        vRules: {
          subscriber: true,
          wellnessOnly: false,
          payMyPremiumElig: true,
          futureEffective: false,
          fsaOnly: false,
          terminated: false,
          katieBeckNoBenefitsElig: false,
          blueCare: true,
        },
      },
    }),
  ),
}));

describe('My Plan Page for BlueCare member', () => {
  afterEach(() => {
    jest.clearAllMocks();
  });

  beforeEach(() => {
    mockedFetch.mockResolvedValueOnce(
      fetchRespWrapper({
        isActive: true,
        subscriberLoggedIn: true,
        lob: 'REGL',
        groupData: {
          groupID: '100000',
          groupCK: '21908',
          groupName: 'Chris B Hall Enterprises',
          parentGroupID: '100001',
          subGroupID: '0001',
          subGroupCK: 28951,
          subGroupName: 'Chris B Hall Enterprises',
          clientID: 'EI',
          policyType: 'INT',
          groupEIN: '620427913',
        },
        networkPrefix: 'QMI',
        subscriberID: '902218823',
        subscriberCK: '91722400',
        subscriberFirstName: 'CHRIS',
        subscriberLastName: 'HALL',
        subscriberTitle: '',
        subscriberDateOfBirth: '08/06/1959',
        subscriberOriginalEffectiveDate: '01/01/2001',
        members: [
          {
            isActive: true,
            memberOrigEffDt: '06/29/2009',
            memberCk: 91722407,
            firstName: 'CHRISTMAS',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '06/29/2009',
            gender: 'M',
            memberSuffix: 6,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '06/15/2009',
            memberCk: 91722406,
            firstName: 'KRISSY',
            middleInitial: 'C',
            lastName: 'HALL',
            title: '',
            memRelation: 'D',
            birthDate: '06/15/2009',
            gender: 'F',
            memberSuffix: 5,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: false,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '05/01/2009',
            memberCk: 91722405,
            firstName: 'CHRISTIAN',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '10/31/2011',
            gender: 'M',
            memberSuffix: 4,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '01/01/2001',
            memberCk: 91722402,
            firstName: 'KRISTY',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'W',
            birthDate: '05/17/1971',
            gender: 'F',
            memberSuffix: 1,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: false,
          },
          {
            isActive: true,
            memberOrigEffDt: '01/01/2001',
            memberCk: 91722401,
            firstName: 'CHRIS',
            middleInitial: 'B',
            lastName: 'HALL',
            title: '',
            memRelation: 'M',
            birthDate: '08/06/1959',
            gender: 'M',
            memberSuffix: 0,
            mailAddressType: 'H',
            workPhone: '1234567890',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'D',
                coverageLevel: '*',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'D',
                planID: 'DEHCNY02',
                effectiveDate: 1509508800000,
                planStartDate: 1451624400000,
                planClassID: 'PPOA',
                networkPlanName: 'DentalBlue Preferred Network',
              },
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: true,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '01/01/2014',
            memberCk: 91722409,
            firstName: 'CHRISTOFF',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '01/01/2000',
            gender: 'M',
            memberSuffix: 8,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: false,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '12/11/2006',
            memberCk: 91722408,
            firstName: 'CHRISTO',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '12/11/2006',
            gender: 'M',
            memberSuffix: 7,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '12/11/2006',
            memberCk: 54363201,
            firstName: 'ChrisBalance',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '12/11/2006',
            gender: 'M',
            memberSuffix: 7,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '12/11/2006',
            memberCk: 877944401,
            firstName: 'CHRISTOCLAIM',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '12/11/2006',
            gender: 'M',
            memberSuffix: 7,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
        ],
        coverageTypes: [
          {
            productType: 'M',
            coverageLevel: 'A',
            exchange: false,
            indvGroupInd: '',
            pedAdultInd: '',
          },
          {
            productType: 'S',
            coverageLevel: 'A',
            exchange: false,
            indvGroupInd: '',
            pedAdultInd: '',
          },
          {
            productType: 'V',
            coverageLevel: 'A',
            exchange: true,
            indvGroupInd: 'Group',
            pedAdultInd: 'Adult',
          },
          {
            productType: 'D',
            coverageLevel: '*',
            exchange: true,
            indvGroupInd: 'Group',
            pedAdultInd: 'Adult',
          },
        ],
        addresses: [
          {
            type: '1',
            address1: 'TEST BLUE ACCESS',
            address2: '',
            address3: '',
            city: 'Chattanooga',
            state: 'TN',
            zipcode: '37412',
            county: 'HAMILTON',
            phone: '',
            email: '',
          },
          {
            type: '2',
            address1: 'TEST 2 BLUE ACCESS',
            address2: '',
            address3: '',
            city: 'Chattanooga',
            state: 'TN',
            zipcode: '37402',
            county: 'HAMILTON',
            phone: '',
            email: '',
          },
          {
            type: 'H',
            address1: '1 CAMERON HILL CIRCLE',
            address2: '',
            address3: '',
            city: 'CHATTANOOGA',
            state: 'TN',
            zipcode: '37402',
            county: 'HAMILTON',
            phone: '4235353065',
            email: '',
          },
        ],
        healthCareAccounts: [],
        esigroupNum: '100000MBPX0806',
        cmcondition: [],
      }),
    );
    mockedAxios.get.mockResolvedValueOnce({
      data: {
        memberServicePhoneNumber: '1-800-565-9000',
      },
    });
    mockedFetch.mockResolvedValueOnce(
      fetchRespWrapper({
        isActive: true,
        subscriberLoggedIn: true,
        lob: 'REGL',
        groupData: {
          groupID: '100000',
          groupCK: '21908',
          groupName: 'Chris B Hall Enterprises',
          parentGroupID: '100001',
          subGroupID: '0001',
          subGroupCK: 28951,
          subGroupName: 'Chris B Hall Enterprises',
          clientID: 'EI',
          policyType: 'INT',
          groupEIN: '620427913',
        },
        networkPrefix: 'QMI',
        subscriberID: '902218823',
        subscriberCK: '91722400',
        subscriberFirstName: 'CHRIS',
        subscriberLastName: 'HALL',
        subscriberTitle: '',
        subscriberDateOfBirth: '08/06/1959',
        subscriberOriginalEffectiveDate: '01/01/2001',
        members: [
          {
            isActive: true,
            memberOrigEffDt: '06/29/2009',
            memberCk: 91722407,
            firstName: 'CHRISTMAS',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '06/29/2009',
            gender: 'M',
            memberSuffix: 6,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '06/15/2009',
            memberCk: 91722406,
            firstName: 'KRISSY',
            middleInitial: 'C',
            lastName: 'HALL',
            title: '',
            memRelation: 'D',
            birthDate: '06/15/2009',
            gender: 'F',
            memberSuffix: 5,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: false,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '05/01/2009',
            memberCk: 91722405,
            firstName: 'CHRISTIAN',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '10/31/2011',
            gender: 'M',
            memberSuffix: 4,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '01/01/2001',
            memberCk: 91722402,
            firstName: 'KRISTY',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'W',
            birthDate: '05/17/1971',
            gender: 'F',
            memberSuffix: 1,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: false,
          },
          {
            isActive: true,
            memberOrigEffDt: '01/01/2001',
            memberCk: 91722401,
            firstName: 'CHRIS',
            middleInitial: 'B',
            lastName: 'HALL',
            title: '',
            memRelation: 'M',
            birthDate: '08/06/1959',
            gender: 'M',
            memberSuffix: 0,
            mailAddressType: 'H',
            workPhone: '1234567890',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'D',
                coverageLevel: '*',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'D',
                planID: 'DEHCNY02',
                effectiveDate: 1509508800000,
                planStartDate: 1451624400000,
                planClassID: 'PPOA',
                networkPlanName: 'DentalBlue Preferred Network',
              },
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: true,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '01/01/2014',
            memberCk: 91722409,
            firstName: 'CHRISTOFF',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '01/01/2000',
            gender: 'M',
            memberSuffix: 8,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: false,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '12/11/2006',
            memberCk: 91722408,
            firstName: 'CHRISTO',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '12/11/2006',
            gender: 'M',
            memberSuffix: 7,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '12/11/2006',
            memberCk: 54363201,
            firstName: 'ChrisBalance',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '12/11/2006',
            gender: 'M',
            memberSuffix: 7,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
          {
            isActive: true,
            memberOrigEffDt: '12/11/2006',
            memberCk: 877944401,
            firstName: 'CHRISTOCLAIM',
            middleInitial: '',
            lastName: 'HALL',
            title: '',
            memRelation: 'S',
            birthDate: '12/11/2006',
            gender: 'M',
            memberSuffix: 7,
            mailAddressType: 'H',
            workPhone: '',
            otherInsurance: [],
            coverageTypes: [
              {
                productType: 'M',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'S',
                coverageLevel: 'A',
                exchange: false,
                indvGroupInd: '',
                pedAdultInd: '',
              },
              {
                productType: 'V',
                coverageLevel: 'A',
                exchange: true,
                indvGroupInd: 'Group',
                pedAdultInd: 'Adult',
              },
            ],
            planDetails: [
              {
                productCategory: 'M',
                planID: 'MBPX0806',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Blue Network P',
              },
              {
                productCategory: 'S',
                planID: 'WSXM0218',
                effectiveDate: 1546318800000,
                planStartDate: 1514782800000,
                planClassID: 'PPOA',
                networkPlanName: 'Wellness Plan',
              },
              {
                productCategory: 'V',
                planID: 'VEMGN002',
                effectiveDate: 1546318800000,
                planStartDate: 1383278400000,
                planClassID: 'PPOA',
                networkPlanName: 'Vision Blue',
              },
            ],
            inXPermissions: true,
            futureEffective: false,
            loggedIn: false,
            hasSocial: true,
            esipharmacyEligible: true,
          },
        ],
        coverageTypes: [
          {
            productType: 'M',
            coverageLevel: 'A',
            exchange: false,
            indvGroupInd: '',
            pedAdultInd: '',
          },
          {
            productType: 'S',
            coverageLevel: 'A',
            exchange: false,
            indvGroupInd: '',
            pedAdultInd: '',
          },
          {
            productType: 'V',
            coverageLevel: 'A',
            exchange: true,
            indvGroupInd: 'Group',
            pedAdultInd: 'Adult',
          },
          {
            productType: 'D',
            coverageLevel: '*',
            exchange: true,
            indvGroupInd: 'Group',
            pedAdultInd: 'Adult',
          },
        ],
        addresses: [
          {
            type: '1',
            address1: 'TEST BLUE ACCESS',
            address2: '',
            address3: '',
            city: 'Chattanooga',
            state: 'TN',
            zipcode: '37412',
            county: 'HAMILTON',
            phone: '',
            email: '',
          },
          {
            type: '2',
            address1: 'TEST 2 BLUE ACCESS',
            address2: '',
            address3: '',
            city: 'Chattanooga',
            state: 'TN',
            zipcode: '37402',
            county: 'HAMILTON',
            phone: '',
            email: '',
          },
          {
            type: 'H',
            address1: '1 CAMERON HILL CIRCLE',
            address2: '',
            address3: '',
            city: 'CHATTANOOGA',
            state: 'TN',
            zipcode: '37402',
            county: 'HAMILTON',
            phone: '4235353065',
            email: '',
          },
        ],
        healthCareAccounts: [],
        esigroupNum: '100000MBPX0806',
        cmcondition: [],
      }),
    );
  });
  it('should render My Plan page UI features for Bluecare member', async () => {
    mockedAxios.get.mockResolvedValueOnce({
      data: null,
    });
    const component = await renderUI();
    screen.getByRole('heading', { name: 'Plan Details' });
    screen.getByText('Plan Type:');
    screen.getByText('BlueCare Medicaid');
    screen.getByText('View More ID Card Options');
    screen.queryByText('View Plan Contact Information');
    screen.getByText('View Other Plan Information');
    screen.getByText('Manage My Plan');
    screen.getByText('Profile Settings');
    screen.getByText('Katie Beckett Banking Info');
    expect(component.baseElement).toMatchSnapshot();
  });
});
