export const genesysConfig = {
  baseConfig: {
    environment: process.env.NEXT_PUBLIC_GENESYS_ENVIRONMENT || 'test',
    deploymentId: process.env.NEXT_PUBLIC_GENESYS_DEPLOYMENT_ID,
    region: process.env.NEXT_PUBLIC_GENESYS_REGION || 'usw2',
  },
  styling: {
    width: '400px',
    height: '600px',
    minWidth: '400px',
    minHeight: '600px',
    position: 'fixed',
    bottom: '20px',
    right: '20px',
    zIndex: 1000,
  },
  testMode: {
    memberId: 'test-member',
    planId: 'test-plan',
    planName: 'Test Plan',
    chatGroup: 'TEST_GROUP',
    chatIDChatBotName: 'TestBot',
    formData: {
      SERV_Type: 'TEST',
      firstname: 'Test',
      lastname: 'User',
      GROUP_ID: 'TEST_GROUP',
      IDCardBotName: 'TestBot',
      IsVisionEligible: false,
      MEMBER_ID: 'test-member',
      coverage_eligibility: true,
      INQ_TYPE: 'MemberPortal',
      IsDentalEligible: false,
      MEMBER_DOB: '1990-01-01',
      LOB: 'TEST',
      lob_group: 'TEST_GROUP',
      IsMedicalEligibile: false,
      Origin: 'MemberPortal',
      Source: 'Web',
    },
  },
};
