import { SiteHeaderSubNavProps } from './composite/SiteHeaderSubNavSection';

const menuNavigation: SiteHeaderSubNavProps[] = [
  {
    id: 1,
    title: 'Find Care & Costs',
    description: 'This is Find Care & Costs',
    category: '',
    showOnMenu: true,
    url: '/findcare',
    qt: {
      // eslint-disable-next-line quotes
      firstParagraph: "Looking for what's covered under your plan?",
      secondParagraph: (
        <p className="pb-1">
          Check out your
          <span className="font-bold">Benefits & Coverages.</span>
        </p>
      ),
      link: '/benefits',
    },
    template: {
      firstCol: 'Find Care',
      secondCol: 'Estimate Costs',
      thirdCol: 'QT',
      fourthCol: '',
    },
    childPages: [
      {
        id: 93,
        title: 'Find a Provider',
        description: 'This is Find a Provider',
        category: 'Find Care',
        showOnMenu: true,
        url: '/findprovider',
        external: true,
      },
      {
        id: 92,
        title: 'Primary Care Options',
        description: 'This is Primary Care Options',
        category: 'Find Care',
        showOnMenu: true,
        url: '/primarycareoptions',
        external: false,
      },
      {
        id: 91,
        title: 'Mental Health Options',
        description: 'This is Mental Health Option',
        category: 'Find Care',
        showOnMenu: true,
        url: '/mentalhealthoptions',
        external: false,
      },
      {
        id: 90,
        title: 'Virtual Care Options',
        description: 'This is Virtual Care Options',
        category: 'Find Care',
        showOnMenu: true,
        url: '/virtualcareoptions',
        external: false,
      },
      {
        id: 89,
        title: 'Price Medical Care',
        description: 'This is Price Medical Care',
        category: 'Estimate Costs',
        showOnMenu: true,
        url: '/pricemedicalcare',
        external: true,
      },
      {
        id: 88,
        title: 'Price Dental Care',
        description: 'This is Price Dental Care',
        category: 'Estimate Costs',
        showOnMenu: true,
        url: '/pricedentalcare',
        external: false,
      },
      {
        id: 87,
        title: 'Price Vision Care',
        description: 'This is Price Vision Care',
        category: 'Estimate Costs',
        showOnMenu: true,
        url: '/pricevisioncare',
        external: true,
      },
      {
        id: 86,
        title: 'Price a Medication',
        description: 'This is Price a Medication',
        category: 'Estimate Costs',
        showOnMenu: true,
        url: '/pricemedication',
        external: true,
      },
    ],
  },
  {
    id: 2,
    title: 'My Plan',
    description: 'This is My Plan',
    category: '',
    showOnMenu: true,
    url: '/myplan',
    template: {
      firstCol: 'Plan Details',
      secondCol: 'Claims',
      thirdCol: 'Spending',
      fourthCol: 'Manage My Plan',
    },
    childPages: [
      {
        id: 99,
        title: 'Benefits & Coverage',
        description: 'This is Benefits & Coverage',
        category: 'Plan Details',
        showOnMenu: true,
        url: '/benefitscoverage',
        external: false,
      },
      {
        id: 98,
        title: 'Plan Documents',
        description: 'This is Plan Documents',
        category: 'Plan Details',
        showOnMenu: true,
        url: '/plandocs',
        external: false,
      },
      {
        id: 97,
        title: 'Services Used',
        description: 'This is Services Used',
        category: 'Plan Details',
        showOnMenu: true,
        url: '/servicesused',
        external: false,
      },
      {
        id: 96,
        title: 'View Claims',
        description: 'This is View Claims',
        category: 'Claims',
        showOnMenu: true,
        url: '/viewclaims',
        external: false,
      },
      {
        id: 95,
        title: 'Prior Authorizations',
        description: 'This is Prior Authorizations',
        category: 'Claims',
        showOnMenu: true,
        url: '/priorauths',
        external: false,
      },
      {
        id: 94,
        title: 'Submit a Claim',
        description: 'This is Submit a Claim',
        category: 'Claims',
        showOnMenu: true,
        url: '/submitclaim',
        external: false,
      },
      {
        id: 78,
        title: 'Balances',
        description: 'This is Balances',
        category: 'Spending',
        showOnMenu: true,
        url: '/balances',
        external: false,
      },
      {
        id: 77,
        title: 'Spending Accounts (HSA, FSA)',
        description: 'This is Spending Accounts (HSA, FSA)',
        category: 'Spending',
        showOnMenu: true,
        url: '/spendingaccounts',
        external: false,
      },
      {
        id: 76,
        title: 'Spending Summary',
        description: 'This is Spending Summary',
        category: 'Spending',
        showOnMenu: true,
        url: '/spendingsummary',
        external: false,
      },
      {
        id: 75,
        title: 'View or Pay Premium',
        description: 'This is View or Pay Premium',
        category: 'Manage My Plan',
        showOnMenu: true,
        url: '/balances',
        external: true,
      },
      {
        id: 74,
        title: 'Enroll in a Health Plan',
        description: 'This is Enroll in a Health Plan',
        category: 'Manage My Plan',
        showOnMenu: true,
        url: '/enrollhealthplan',
        external: true,
      },
      {
        id: 73,
        title: 'Report Other Health Insurance',
        description: 'This is Report Other Health Insurance',
        category: 'Manage My Plan',
        showOnMenu: true,
        url: '/reportotherhealthinsurance',
        external: false,
      },
    ],
  },
  {
    id: 3,
    title: 'My Health',
    description: 'This is My Health',
    category: '',
    showOnMenu: true,
    url: '/myhealth',
    qt: {
      firstParagraph:
        'Looking for a virtual care provider for mental health or physical therapy?',
      secondParagraph: (
        <p className="pb-1">
          View <span className="font-bold">Virtual Care Options.</span>
        </p>
      ),
      link: '/virtualcare',
    },
    template: {
      firstCol: 'Wellness',
      secondCol: 'Advice & Support',
      thirdCol: 'QT',
      fourthCol: '',
    },
    childPages: [
      {
        id: 85,
        title: 'Wellness Rewards',
        description: 'This is Wellness Rewards',
        category: 'Wellness',
        showOnMenu: true,
        url: '/wellnessrewards',
        external: true,
      },
      {
        id: 84,
        title: 'Member Wellness Canter',
        description: 'This is Member Wellness Canter',
        category: 'Wellness',
        showOnMenu: true,
        url: '/memberwellnesscenter',
        external: true,
      },
      {
        id: 83,
        title: 'My Primary Care Provider',
        description: 'This is My Primary Care Provider',
        category: 'Wellness',
        showOnMenu: true,
        url: '/myprimarycareprov',
        external: false,
      },
      {
        id: 82,
        title: 'Member Discounts',
        description: 'This is Member Discounts',
        category: 'Wellness',
        showOnMenu: true,
        url: '/memberdiscounts',
        external: true,
      },
      {
        id: 81,
        title: 'Health Programs & Resources',
        description: 'This is Health Programs & Resources',
        category: 'Advice & Support',
        showOnMenu: true,
        url: '/healthprogramsresources',
        external: false,
      },
      {
        id: 80,
        title: 'Dental Health Library',
        description: 'This is Dental Health Library',
        category: 'Advice & Support',
        showOnMenu: true,
        url: 'https://bcbstwelltuned.com/',
        external: true,
      },
      {
        id: 79,
        title: 'Health Library',
        description: 'This is Health Library',
        category: 'Advice & Support',
        showOnMenu: true,
        url: 'https://www.healthwise.net/bcbst/Content/CustDocument.aspx?XML=STUB.XML&XSL=CD.FRONTPAGE.XSL&sv=881d5daa-1051-f477-21f5-a05f3e6cdf78',
        external: true,
      },
      {
        id: 78,
        title: 'WellTuned Blog',
        description: 'This is WellTuned Blog',
        category: 'Advice & Support',
        showOnMenu: true,
        url: 'https://bcbstwelltuned.com/',
        external: true,
      },
    ],
  },
  {
    id: 4,
    title: 'Pharmacy',
    description: 'This is Pharmacy',
    category: '',
    showOnMenu: true,
    url: '/pharmacy',
    qt: {
      firstParagraph: 'Your pharmacy benefits are managed by CVS Caremark.',
      secondParagraph: (
        <p className="pb-1">
          <span className="font-bold">A caremark.com</span> account will let you
          get prescriptions by mail, price a medication and more.
        </p>
      ),
      link: '/pharmacy',
    },
    shortLinks: [
      { title: 'Pharmacy Claims', link: '/claims' },
      { title: 'Pharmacy Spending', link: '/pharmacyspending' },
    ],
    template: {
      firstCol: 'QT',
      secondCol: 'Manage My Prescriptions',
      thirdCol: 'Resources & Support',
      fourthCol: 'LINKS',
    },
    childPages: [
      {
        id: 72,
        title: 'My Prescriptions',
        description: 'This is My Prescriptions',
        category: 'Manage My Prescriptions',
        showOnMenu: true,
        url: '/myprescription',
        external: true,
      },
      {
        id: 71,
        title: 'Price a Medication',
        description: 'This is Price a Medication',
        category: 'Manage My Prescriptions',
        showOnMenu: true,
        url: '/pricemedication',
        external: true,
      },
      {
        id: 70,
        title: 'Mail Order',
        description: 'This is Mail Order',
        category: 'Manage My Prescriptions',
        showOnMenu: true,
        url: '/mailorder',
        external: true,
      },
      {
        id: 69,
        title: 'Pharmacy Documents & Forms',
        description: 'This is Pharmacy Documents & Forms',
        category: 'Resources & Support',
        showOnMenu: true,
        url: '/pharmacydocsforms',
        external: false,
      },
      {
        id: 81,
        title: 'Pharmacy FAQ',
        description: 'This is Pharmacy FAQ',
        category: 'Resources & Support',
        showOnMenu: true,
        url: '/pharmacyfaq',
        external: false,
      },
    ],
  },
  {
    id: 5,
    title: 'Support',
    description: 'This is Support',
    category: '',
    showOnMenu: true,
    url: '/support',
    qt: {
      // eslint-disable-next-line quotes
      firstParagraph: "We're here to help.",
      secondParagraph: (
        <p className="pb-1">
          <span className="font-bold">Start a chat</span> or call us at
          [1-800-000-0000].
        </p>
      ),
      link: '/support',
    },
    template: {
      firstCol: 'QT',
      secondCol: 'Support',
      thirdCol: '',
      fourthCol: '',
    },
    childPages: [
      {
        id: 82,
        title: 'Frequently Asked Questions',
        description: 'Frequently Asked Questions',
        category: 'Support',
        showOnMenu: true,
        url: '/frequentlyAskedQuestions',
        external: false,
      },
      {
        id: 83,
        title: 'Health Insurance Glossary',
        description: 'Health Insurance Glossary',
        category: 'Support',
        showOnMenu: true,
        url: 'https://www.healthcare.gov/glossary/',
        external: true,
      },
      {
        id: 84,
        title: 'Find a Form',
        description: 'Find a Form',
        category: 'Support',
        showOnMenu: true,
        url: 'https://www.bcbst.com/use-insurance/documents-forms/',
        external: false,
      },
      {
        id: 85,
        title: 'Share Website Feedback',
        description: 'Share Website Feedback',
        category: 'Support',
        showOnMenu: true,
        url: '/shareWebsiteFeedback',
        external: false,
      },
    ],
  },
];

export default menuNavigation;
