export const AUTH_FUNCTION_MAP = {
  delinquent: 'CLAIMSHOLD',
  katieBeckNoBenefitsElig: 'KB_NO_BENEFITS',
  myPCPElig: 'MYPCPELIGIBLE',
  identityProtectionServices: 'IDPROTECTELIGIBLE',
  otcEnable: 'OTCEnable',
  showPharmacyTab: 'ENABLE_PHAR_TAB',
  chipRewardsEligible: 'CHIPELIGIBLE',
  blueHealthRewardsEligible: 'BLUEHEALTHREWARDS', //TODO We can consolidate these - two auth functions are not necessary for rewards
  bluePerksElig: 'BLUEPRKS',
  amplifyMember: 'AMPLIFYMEMBER',
  myStrengthCompleteEligible: 'TELADOC_MYSTRENGTHCOMPLETE',
  mentalHealthSupport: 'MENTAL_HEALTH_SUPPORT',
  primary360Eligible: 'TELADOC_PRIMARY360',
  individualSBCEligible: 'INDIVIDUAL_SBC_ELIGIBLE',
  medicareAdvantageGroupIndicator: 'MedicareAdvantageGroupIndicator',
  isCondensedExperience: 'CONDENSED_EXPERIENCE', //TODO duplicate
  otherInsuranceEligible: 'COBUPDATEELIGIBLE',
  enRollEligible: 'ENROLLELIGIBLE',
  enableBenefitChange: 'ENABLE_BENEFIT_CHANGE_TAB',
  dentalCostEligible: 'DENTALCOSTELIGIBLE',
  enableCostTools: 'ENABLE_COST_TOOLS',
  payMyPremiumElig: 'PAYMYPREMIUMELIGIBLE',
  hingeHealthEligible: 'HINGE_HEALTH_ELIGIBLE',
  groupRenewalBeforeTodaysDate: 'GROUP_RENEWAL_DATE_BEFORE_TODAY',
  healthCoachElig: 'HEALTHCOACHELIGIBLE',
  isAmplifyMem: 'AMPLIFYMEMBER',
  diabetesPreventionEligible: 'TELADOC_DIABETESPREVENTION',
  cmEnable: 'careManagementExclusion',
  ohdEligible: 'OHDELIGIBLE',
  fsaHraEligible: 'FSAHRAELIGIBLE',
  flexibleSpendingAccount: 'FlexibleSpendingAccount',
  healthReimbursementAccount: 'HealthReimbursementAccount',
  hypertensionMgmt: 'TELADOC_HYPERTENSIONMGMT',
  consumerMedicalEligible: 'CONSUMER_MEDICAL_ELIGIBLE',
  phsEligible: 'PHSELIGIBLE',
  allMedicareAdvantageEligible: 'AllMedicareAdvantage',
  rxChoiceEligible: 'RX_CHOICE_ELIGIBLE',
  rxEssentialEligible: 'RX_ESSENTIAL_ELIGIBLE',
  rxEssentialPlusEligible: 'RX_ESSENTIAL_PLUS_ELIGIBLE',
  rsPreferredEligible: 'RX_PREFERRED_ELIGIBLE',
  medicarePrescriptionPaymentPlanEligible:
    'MEDICARE_PRESCRIPTION_PAYMENT_PLAN_ELIGIBLE',
  diabetesManagementEligible: 'TELADOC_DIABETESMGMT',
  questSelectEligible: 'QUEST_SELECT',
  isEmboldHealth: 'EMBOLD_HEALTH',
  teladocEligible: 'TELADOC',
  prevYearMedical: 'PREV_YEAR_MEDICAL', // TODO authFunction to be created
  prevYearFullyInsured: 'PREV_YEAR_FULLY_INSURED', // TODO authFunction to be created
  phaMemberEligible: 'PHACommercialEligible',
  isMskEligible: 'MSK_ELIGIBLE',
  fullyInsuredHealthyMaternity: 'FIHEALTHYMATERNITY',
  enableHealthyMaternity: 'HEALTHYMATERNITY',
  isWellnessOnlyBenefitsQV: 'WellnessOnlyBenefitsQV_VisibilityRule',
  isHighDeductiblePlanMember: 'HighDeductiblePlanMember',
};
