export const MEMBER_ATTRIBUTES_LIST = [
  'active',
  'termed',
  'futureEffective',
  'selfFunded',
  'fullyInsured',
  'levelFunded',
  'delinquent',
  'subscriber',
  'commercial',
  'individual',
  'medical',
  'dental',
  'vision',
  'wellness',
  'wellnessOnly',
  'spendingAccounts',
  'externalSpendingAcct',
  'teladoc',
  'pharmacy',
  'amplifyHealth',
  'premiumHealth',
  'benefitBooklet',
  'employerProvidedBenefits',
  'fsaOnly',
  'terminated',
  'katieBeckNoBenefitsElig',
  'blueCare',
  'myPCPElig',
  'chipRewardsEligible',
  'blueHealthRewardsEligible',
  'bluePerksElig',
  'amplifyMember',
  'primary360Eligible',
  'mentalHealthSupport',
  'commercialFull',
  'individualSBCEligible',
  'medicareAdvantageGroupIndicator',
  'isCondensedExperience',
  'enRollEligible',
  'enableBenefitChange',
  'medicare',
  'enableCostTools',
  'dentalCostsEligible',
  'payMyPremiumElig',
  'mentalHealthSupport',
  'myStrengthCompleteEligible',
  'primary360Eligible',
  'hingeHealthEligible',
  'groupRenewalDateBeforeTodaysDate',
  'healthCoachElig',
  'indivEHBUser',
  'groupEHBUser',
  'isAmplifyMem',
  'cmEnable',
] as const;

export type VisibilityRule = (typeof MEMBER_ATTRIBUTES_LIST)[number];
export type VisibilityRules = {
  [key in VisibilityRule]?: boolean;
};
