import { ClaimDetails } from '@/models/claim_details';

export const priorAuthorizationData: ClaimDetails[] = [
  {
    id: 'Claim1',
    claimStatus: 'Pending',
    claimType: 'Medical',
    claimTotal: null,
    issuer: 'Physical Therapy',
    memberName: 'Chris Hall',
    serviceDate: '04/06/23',
    claimInfo: {},
    memberId: '23',
    claimStatusCode: 1,
    columns: [
      { label: 'Referred by', value: 'Anand Patel', defaultValue: 'N/A' },
      { label: 'Referred to', value: 'Anand Patel', defaultValue: 'N/A' },
    ],
  },
  {
    id: 'Claim2',
    claimStatus: 'Approved',
    claimType: 'Medical',
    claimTotal: null,
    issuer: 'Magnetic Resonance Imaging (MRI)',
    memberName: 'Chris Hall',
    serviceDate: '01/23/23',
    claimInfo: {},
    memberId: '23',
    claimStatusCode: 2,
    columns: [
      { label: 'Referred by', value: null, defaultValue: 'N/A' },
      { label: 'Referred to', value: null, defaultValue: 'N/A' },
    ],
  },
  {
    id: 'Claim3',
    claimStatus: 'Partial Approval',
    claimType: 'Medical',
    claimTotal: null,
    issuer: 'Continuous Positive Airway Pressure Machi…',
    memberName: 'Chris Hall',
    serviceDate: '08/10/23',
    claimInfo: {},
    memberId: '23',
    claimStatusCode: 3,
    columns: [
      { label: 'Referred by', value: null, defaultValue: 'N/A' },
      { label: 'Referred to', value: 'Anand Patel', defaultValue: 'N/A' },
    ],
  },
  {
    id: 'Claim4',
    claimStatus: 'Denied',
    claimType: 'Medical',
    claimTotal: null,
    issuer: 'Home Health Services',
    memberName: 'Chris Hall',
    serviceDate: '07/05/23',
    claimInfo: {},
    memberId: '23',
    claimStatusCode: 4,
    columns: [
      {
        label: 'Referred by',
        value: 'Home Health Services',
        defaultValue: 'N/A',
      },
      { label: 'Referred to', value: null, defaultValue: 'N/A' },
    ],
  },
  {
    id: 'Claim5',
    claimStatus: 'Approved',
    claimType: 'Medical',
    claimTotal: null,
    issuer: 'Brittant Johnson',
    memberName: 'Chris Hall',
    serviceDate: '07/04/23',
    claimInfo: {},
    memberId: '23',
    claimStatusCode: 2,
    columns: [
      { label: 'Referred by', value: null, defaultValue: 'N/A' },
      { label: 'Referred to', value: null, defaultValue: 'N/A' },
    ],
  },
];
